//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.mapper.jaxb;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ivoa.vodml.mapper.jaxb package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ivoa.vodml.mapper.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TAPSCHEMA }
     * 
     * @return
     *     the new instance of {@link TAPSCHEMA }
     */
    public TAPSCHEMA createTAPSCHEMA() {
        return new TAPSCHEMA();
    }

    /**
     * Create an instance of {@link Schema }
     * 
     * @return
     *     the new instance of {@link Schema }
     */
    public Schema createSchema() {
        return new Schema();
    }

    /**
     * Create an instance of {@link TAPTABLE }
     * 
     * @return
     *     the new instance of {@link TAPTABLE }
     */
    public TAPTABLE createTAPTABLE() {
        return new TAPTABLE();
    }

    /**
     * Create an instance of {@link Column }
     * 
     * @return
     *     the new instance of {@link Column }
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link Table }
     * 
     * @return
     *     the new instance of {@link Table }
     */
    public Table createTable() {
        return new Table();
    }

}
