//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:45:59 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ivoa.net/xml/VO-DML_Mapper/v1.0")
package org.ivoa.vodml.mapper.jaxb;
