//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.votable_1_4.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Deprecated in Version 1.2
 * 
 * <p>Java class for CoordinateSystem complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="CoordinateSystem">
 *   <simpleContent>
 *     <extension base="<http://www.w3.org/2001/XMLSchema>string">
 *       <attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       <attribute name="equinox" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}astroYear" />
 *       <attribute name="epoch" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}astroYear" />
 *       <attribute name="system" default="eq_FK5">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             <enumeration value="eq_FK4"/>
 *             <enumeration value="eq_FK5"/>
 *             <enumeration value="ICRS"/>
 *             <enumeration value="ecl_FK4"/>
 *             <enumeration value="ecl_FK5"/>
 *             <enumeration value="galactic"/>
 *             <enumeration value="supergalactic"/>
 *             <enumeration value="xy"/>
 *             <enumeration value="barycentric"/>
 *             <enumeration value="geo_app"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoordinateSystem", propOrder = {
    "value"
})
public class CoordinateSystem {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "equinox")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String equinox;
    @XmlAttribute(name = "epoch")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String epoch;
    @XmlAttribute(name = "system")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String system;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the equinox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquinox() {
        return equinox;
    }

    /**
     * Sets the value of the equinox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquinox(String value) {
        this.equinox = value;
    }

    /**
     * Gets the value of the epoch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpoch() {
        return epoch;
    }

    /**
     * Sets the value of the epoch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpoch(String value) {
        this.epoch = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystem() {
        if (system == null) {
            return "eq_FK5";
        } else {
            return system;
        }
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystem(String value) {
        this.system = value;
    }

}
