//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.votable_1_4.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Added in Version 1.2: INFO for diagnostics
 * 
 * <p>Java class for Data complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Data">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <choice>
 *           <element name="TABLEDATA" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}TableData"/>
 *           <element name="BINARY" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}Binary"/>
 *           <element name="BINARY2" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}Binary2"/>
 *           <element name="FITS" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}FITS"/>
 *         </choice>
 *         <element name="INFO" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}Info" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Data", propOrder = {
    "fits",
    "binary2",
    "binary",
    "tabledata",
    "infos"
})
public class Data {

    @XmlElement(name = "FITS")
    protected FITS fits;
    @XmlElement(name = "BINARY2")
    protected Binary2 binary2;
    @XmlElement(name = "BINARY")
    protected Binary binary;
    @XmlElement(name = "TABLEDATA")
    protected TableData tabledata;
    @XmlElement(name = "INFO")
    protected List<Info> infos;

    /**
     * Gets the value of the fits property.
     * 
     * @return
     *     possible object is
     *     {@link FITS }
     *     
     */
    public FITS getFITS() {
        return fits;
    }

    /**
     * Sets the value of the fits property.
     * 
     * @param value
     *     allowed object is
     *     {@link FITS }
     *     
     */
    public void setFITS(FITS value) {
        this.fits = value;
    }

    /**
     * Gets the value of the binary2 property.
     * 
     * @return
     *     possible object is
     *     {@link Binary2 }
     *     
     */
    public Binary2 getBINARY2() {
        return binary2;
    }

    /**
     * Sets the value of the binary2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Binary2 }
     *     
     */
    public void setBINARY2(Binary2 value) {
        this.binary2 = value;
    }

    /**
     * Gets the value of the binary property.
     * 
     * @return
     *     possible object is
     *     {@link Binary }
     *     
     */
    public Binary getBINARY() {
        return binary;
    }

    /**
     * Sets the value of the binary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Binary }
     *     
     */
    public void setBINARY(Binary value) {
        this.binary = value;
    }

    /**
     * Gets the value of the tabledata property.
     * 
     * @return
     *     possible object is
     *     {@link TableData }
     *     
     */
    public TableData getTABLEDATA() {
        return tabledata;
    }

    /**
     * Sets the value of the tabledata property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableData }
     *     
     */
    public void setTABLEDATA(TableData value) {
        this.tabledata = value;
    }

    /**
     * Gets the value of the infos property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the infos property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getINFOS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Info }
     * </p>
     * 
     * 
     * @return
     *     The value of the infos property.
     */
    public List<Info> getINFOS() {
        if (infos == null) {
            infos = new ArrayList<>();
        }
        return this.infos;
    }

}
