//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.votable_1_4.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Deprecated in Version 1.1
 * 
 * <p>Java class for Definitions complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Definitions">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded" minOccurs="0">
 *         <element name="COOSYS" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}CoordinateSystem"/>
 *         <element name="PARAM" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}Param"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Definitions", propOrder = {
    "coosysAndPARAMS"
})
public class Definitions {

    @XmlElements({
        @XmlElement(name = "COOSYS", type = CoordinateSystem.class),
        @XmlElement(name = "PARAM", type = Param.class)
    })
    protected List<Object> coosysAndPARAMS;

    /**
     * Gets the value of the coosysAndPARAMS property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coosysAndPARAMS property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCOOSYSAndPARAMS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoordinateSystem }
     * {@link Param }
     * </p>
     * 
     * 
     * @return
     *     The value of the coosysAndPARAMS property.
     */
    public List<Object> getCOOSYSAndPARAMS() {
        if (coosysAndPARAMS == null) {
            coosysAndPARAMS = new ArrayList<>();
        }
        return this.coosysAndPARAMS;
    }

}
