//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.votable_1_4.jaxb;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ivoa.votable_1_4.jaxb package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _VODMLReferenceIDREF_QNAME = new QName("http://www.ivoa.net/xml/VOTable/v1.4_vodml", "IDREF");
    private static final QName _VODMLReferenceREMOTEREFERENCE_QNAME = new QName("http://www.ivoa.net/xml/VOTable/v1.4_vodml", "REMOTEREFERENCE");
    private static final QName _VODMLReferenceFOREIGNKEY_QNAME = new QName("http://www.ivoa.net/xml/VOTable/v1.4_vodml", "FOREIGNKEY");
    private static final QName _VODMLCompositionEXTINSTANCES_QNAME = new QName("http://www.ivoa.net/xml/VOTable/v1.4_vodml", "EXTINSTANCES");
    private static final QName _VODMLAttributeCOLUMN_QNAME = new QName("http://www.ivoa.net/xml/VOTable/v1.4_vodml", "COLUMN");
    private static final QName _VODMLAttributeCONSTANT_QNAME = new QName("http://www.ivoa.net/xml/VOTable/v1.4_vodml", "CONSTANT");
    private static final QName _VODMLAttributeLITERAL_QNAME = new QName("http://www.ivoa.net/xml/VOTable/v1.4_vodml", "LITERAL");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ivoa.votable_1_4.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VOTABLE }
     * 
     * @return
     *     the new instance of {@link VOTABLE }
     */
    public VOTABLE createVOTABLE() {
        return new VOTABLE();
    }

    /**
     * Create an instance of {@link VODML }
     * 
     * @return
     *     the new instance of {@link VODML }
     */
    public VODML createVODML() {
        return new VODML();
    }

    /**
     * Create an instance of {@link AnyTEXT }
     * 
     * @return
     *     the new instance of {@link AnyTEXT }
     */
    public AnyTEXT createAnyTEXT() {
        return new AnyTEXT();
    }

    /**
     * Create an instance of {@link Definitions }
     * 
     * @return
     *     the new instance of {@link Definitions }
     */
    public Definitions createDefinitions() {
        return new Definitions();
    }

    /**
     * Create an instance of {@link CoordinateSystem }
     * 
     * @return
     *     the new instance of {@link CoordinateSystem }
     */
    public CoordinateSystem createCoordinateSystem() {
        return new CoordinateSystem();
    }

    /**
     * Create an instance of {@link Group }
     * 
     * @return
     *     the new instance of {@link Group }
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Param }
     * 
     * @return
     *     the new instance of {@link Param }
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Info }
     * 
     * @return
     *     the new instance of {@link Info }
     */
    public Info createInfo() {
        return new Info();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     * @return
     *     the new instance of {@link Resource }
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Min }
     * 
     * @return
     *     the new instance of {@link Min }
     */
    public Min createMin() {
        return new Min();
    }

    /**
     * Create an instance of {@link Max }
     * 
     * @return
     *     the new instance of {@link Max }
     */
    public Max createMax() {
        return new Max();
    }

    /**
     * Create an instance of {@link Option }
     * 
     * @return
     *     the new instance of {@link Option }
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link Values }
     * 
     * @return
     *     the new instance of {@link Values }
     */
    public Values createValues() {
        return new Values();
    }

    /**
     * Create an instance of {@link Link }
     * 
     * @return
     *     the new instance of {@link Link }
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Field }
     * 
     * @return
     *     the new instance of {@link Field }
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link FieldRef }
     * 
     * @return
     *     the new instance of {@link FieldRef }
     */
    public FieldRef createFieldRef() {
        return new FieldRef();
    }

    /**
     * Create an instance of {@link ParamRef }
     * 
     * @return
     *     the new instance of {@link ParamRef }
     */
    public ParamRef createParamRef() {
        return new ParamRef();
    }

    /**
     * Create an instance of {@link Data }
     * 
     * @return
     *     the new instance of {@link Data }
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link TableData }
     * 
     * @return
     *     the new instance of {@link TableData }
     */
    public TableData createTableData() {
        return new TableData();
    }

    /**
     * Create an instance of {@link Td }
     * 
     * @return
     *     the new instance of {@link Td }
     */
    public Td createTd() {
        return new Td();
    }

    /**
     * Create an instance of {@link Tr }
     * 
     * @return
     *     the new instance of {@link Tr }
     */
    public Tr createTr() {
        return new Tr();
    }

    /**
     * Create an instance of {@link FITS }
     * 
     * @return
     *     the new instance of {@link FITS }
     */
    public FITS createFITS() {
        return new FITS();
    }

    /**
     * Create an instance of {@link Binary }
     * 
     * @return
     *     the new instance of {@link Binary }
     */
    public Binary createBinary() {
        return new Binary();
    }

    /**
     * Create an instance of {@link Binary2 }
     * 
     * @return
     *     the new instance of {@link Binary2 }
     */
    public Binary2 createBinary2() {
        return new Binary2();
    }

    /**
     * Create an instance of {@link Stream }
     * 
     * @return
     *     the new instance of {@link Stream }
     */
    public Stream createStream() {
        return new Stream();
    }

    /**
     * Create an instance of {@link Table }
     * 
     * @return
     *     the new instance of {@link Table }
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link VODMLGlobals }
     * 
     * @return
     *     the new instance of {@link VODMLGlobals }
     */
    public VODMLGlobals createVODMLGlobals() {
        return new VODMLGlobals();
    }

    /**
     * Create an instance of {@link VODMLInstanceTemplates }
     * 
     * @return
     *     the new instance of {@link VODMLInstanceTemplates }
     */
    public VODMLInstanceTemplates createVODMLInstanceTemplates() {
        return new VODMLInstanceTemplates();
    }

    /**
     * Create an instance of {@link Model }
     * 
     * @return
     *     the new instance of {@link Model }
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link VODMLObject }
     * 
     * @return
     *     the new instance of {@link VODMLObject }
     */
    public VODMLObject createVODMLObject() {
        return new VODMLObject();
    }

    /**
     * Create an instance of {@link VODMLPrimitive }
     * 
     * @return
     *     the new instance of {@link VODMLPrimitive }
     */
    public VODMLPrimitive createVODMLPrimitive() {
        return new VODMLPrimitive();
    }

    /**
     * Create an instance of {@link VODMLLiteral }
     * 
     * @return
     *     the new instance of {@link VODMLLiteral }
     */
    public VODMLLiteral createVODMLLiteral() {
        return new VODMLLiteral();
    }

    /**
     * Create an instance of {@link VODMLOptionMapping }
     * 
     * @return
     *     the new instance of {@link VODMLOptionMapping }
     */
    public VODMLOptionMapping createVODMLOptionMapping() {
        return new VODMLOptionMapping();
    }

    /**
     * Create an instance of {@link VODMLFieldOrParamRef }
     * 
     * @return
     *     the new instance of {@link VODMLFieldOrParamRef }
     */
    public VODMLFieldOrParamRef createVODMLFieldOrParamRef() {
        return new VODMLFieldOrParamRef();
    }

    /**
     * Create an instance of {@link VODMLRole }
     * 
     * @return
     *     the new instance of {@link VODMLRole }
     */
    public VODMLRole createVODMLRole() {
        return new VODMLRole();
    }

    /**
     * Create an instance of {@link VODMLAttribute }
     * 
     * @return
     *     the new instance of {@link VODMLAttribute }
     */
    public VODMLAttribute createVODMLAttribute() {
        return new VODMLAttribute();
    }

    /**
     * Create an instance of {@link VODMLComposition }
     * 
     * @return
     *     the new instance of {@link VODMLComposition }
     */
    public VODMLComposition createVODMLComposition() {
        return new VODMLComposition();
    }

    /**
     * Create an instance of {@link VODMLReference }
     * 
     * @return
     *     the new instance of {@link VODMLReference }
     */
    public VODMLReference createVODMLReference() {
        return new VODMLReference();
    }

    /**
     * Create an instance of {@link VODMLORMReference }
     * 
     * @return
     *     the new instance of {@link VODMLORMReference }
     */
    public VODMLORMReference createVODMLORMReference() {
        return new VODMLORMReference();
    }

    /**
     * Create an instance of {@link VODMLObjectIdentifierField }
     * 
     * @return
     *     the new instance of {@link VODMLObjectIdentifierField }
     */
    public VODMLObjectIdentifierField createVODMLObjectIdentifierField() {
        return new VODMLObjectIdentifierField();
    }

    /**
     * Create an instance of {@link VODMLObjectIdentifier }
     * 
     * @return
     *     the new instance of {@link VODMLObjectIdentifier }
     */
    public VODMLObjectIdentifier createVODMLObjectIdentifier() {
        return new VODMLObjectIdentifier();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", name = "IDREF", scope = VODMLReference.class)
    @XmlIDREF
    public JAXBElement<Object> createVODMLReferenceIDREF(Object value) {
        return new JAXBElement<>(_VODMLReferenceIDREF_QNAME, Object.class, VODMLReference.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", name = "REMOTEREFERENCE", scope = VODMLReference.class)
    public JAXBElement<String> createVODMLReferenceREMOTEREFERENCE(String value) {
        return new JAXBElement<>(_VODMLReferenceREMOTEREFERENCE_QNAME, String.class, VODMLReference.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VODMLORMReference }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link VODMLORMReference }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", name = "FOREIGNKEY", scope = VODMLReference.class)
    public JAXBElement<VODMLORMReference> createVODMLReferenceFOREIGNKEY(VODMLORMReference value) {
        return new JAXBElement<>(_VODMLReferenceFOREIGNKEY_QNAME, VODMLORMReference.class, VODMLReference.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", name = "EXTINSTANCES", scope = VODMLComposition.class)
    @XmlIDREF
    public JAXBElement<Object> createVODMLCompositionEXTINSTANCES(Object value) {
        return new JAXBElement<>(_VODMLCompositionEXTINSTANCES_QNAME, Object.class, VODMLComposition.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VODMLFieldOrParamRef }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link VODMLFieldOrParamRef }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", name = "COLUMN", scope = VODMLAttribute.class)
    public JAXBElement<VODMLFieldOrParamRef> createVODMLAttributeCOLUMN(VODMLFieldOrParamRef value) {
        return new JAXBElement<>(_VODMLAttributeCOLUMN_QNAME, VODMLFieldOrParamRef.class, VODMLAttribute.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VODMLFieldOrParamRef }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link VODMLFieldOrParamRef }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", name = "CONSTANT", scope = VODMLAttribute.class)
    public JAXBElement<VODMLFieldOrParamRef> createVODMLAttributeCONSTANT(VODMLFieldOrParamRef value) {
        return new JAXBElement<>(_VODMLAttributeCONSTANT_QNAME, VODMLFieldOrParamRef.class, VODMLAttribute.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VODMLLiteral }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link VODMLLiteral }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", name = "LITERAL", scope = VODMLAttribute.class)
    public JAXBElement<VODMLLiteral> createVODMLAttributeLITERAL(VODMLLiteral value) {
        return new JAXBElement<>(_VODMLAttributeLITERAL_QNAME, VODMLLiteral.class, VODMLAttribute.class, value);
    }

}
