//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.votable_1_4.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VODMLAttribute complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="VODMLAttribute">
 *   <complexContent>
 *     <extension base="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLRole">
 *       <choice>
 *         <choice maxOccurs="unbounded">
 *           <element name="COLUMN" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLFieldOrParamRef"/>
 *           <element name="CONSTANT" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLFieldOrParamRef"/>
 *           <element name="LITERAL" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLLiteral"/>
 *         </choice>
 *         <element name="INSTANCE" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLObject" maxOccurs="unbounded"/>
 *       </choice>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLAttribute", propOrder = {
    "instances",
    "columnsAndCONSTANTSAndLITERALS"
})
public class VODMLAttribute
    extends VODMLRole
{

    /**
     * Structured value, must be instance of DataType
     * 
     */
    @XmlElement(name = "INSTANCE")
    protected List<VODMLObject> instances;
    /**
     * When used inside a "template" structured type, i.e. one defined inside a TABLE element,
     *                     this allows one to indicate a FIELD representing the attribute.
     * 
     */
    @XmlElementRefs({
        @XmlElementRef(name = "COLUMN", namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CONSTANT", namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "LITERAL", namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<? extends VODMLPrimitive>> columnsAndCONSTANTSAndLITERALS;

    /**
     * Structured value, must be instance of DataType
     * 
     * Gets the value of the instances property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instances property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getINSTANCES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VODMLObject }
     * </p>
     * 
     * 
     * @return
     *     The value of the instances property.
     */
    public List<VODMLObject> getINSTANCES() {
        if (instances == null) {
            instances = new ArrayList<>();
        }
        return this.instances;
    }

    /**
     * When used inside a "template" structured type, i.e. one defined inside a TABLE element,
     *                     this allows one to indicate a FIELD representing the attribute.
     * 
     * Gets the value of the columnsAndCONSTANTSAndLITERALS property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the columnsAndCONSTANTSAndLITERALS property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCOLUMNSAndCONSTANTSAndLITERALS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link VODMLFieldOrParamRef }{@code >}
     * {@link JAXBElement }{@code <}{@link VODMLFieldOrParamRef }{@code >}
     * {@link JAXBElement }{@code <}{@link VODMLLiteral }{@code >}
     * </p>
     * 
     * 
     * @return
     *     The value of the columnsAndCONSTANTSAndLITERALS property.
     */
    public List<JAXBElement<? extends VODMLPrimitive>> getCOLUMNSAndCONSTANTSAndLITERALS() {
        if (columnsAndCONSTANTSAndLITERALS == null) {
            columnsAndCONSTANTSAndLITERALS = new ArrayList<>();
        }
        return this.columnsAndCONSTANTSAndLITERALS;
    }

}
