//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.votable_1_4.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A reference to an object identified by that object's identifier.
 *         The referenced object must be stored in a TABLE and must have been annotated with an explicit identifier.
 * 
 * <p>Java class for VODMLORMReference complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="VODMLORMReference">
 *   <complexContent>
 *     <extension base="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLObjectIdentifier">
 *       <sequence>
 *         <element name="TARGETID" type="{http://www.w3.org/2001/XMLSchema}IDREF" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLORMReference", propOrder = {
    "targetid"
})
public class VODMLORMReference
    extends VODMLObjectIdentifier
{

    /**
     * This element MAY be used to provide a IDREF to the (ID of a) VODMLObject template annotating
     *                 the TABLE containing the referenced object.
     * 
     */
    @XmlElement(name = "TARGETID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object targetid;

    /**
     * This element MAY be used to provide a IDREF to the (ID of a) VODMLObject template annotating
     *                 the TABLE containing the referenced object.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTARGETID() {
        return targetid;
    }

    /**
     * Sets the value of the targetid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     * @see #getTARGETID()
     */
    public void setTARGETID(Object value) {
        this.targetid = value;
    }

}
