//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.votable_1_4.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for VODMLObject complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="VODMLObject">
 *   <complexContent>
 *     <extension base="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLInstance">
 *       <sequence>
 *         <element name="PRIMARYKEY" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLObjectIdentifier" minOccurs="0"/>
 *         <element name="CONTAINER" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLReference" minOccurs="0"/>
 *         <element name="ATTRIBUTE" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLAttribute" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="COMPOSITION" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLComposition" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="REFERENCE" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLReference" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLObject", propOrder = {
    "primarykey",
    "container",
    "attributes",
    "compositions",
    "references"
})
public class VODMLObject
    extends VODMLInstance
{

    /**
     * Objects, i.e. ObjectType instances, can have a unique identifier which can be used in ORM-like references.
     * 
     */
    @XmlElement(name = "PRIMARYKEY")
    protected VODMLObjectIdentifier primarykey;
    /**
     * Possible reference to a parent container of the object. May be given when the objects is not already
     *               contained in a colleciton on the parent object.
     *               Note, a VODMLReference can have multiple instances, but a CONTAINER MUST have only 1 instance.
     * 
     */
    @XmlElement(name = "CONTAINER")
    protected VODMLReference container;
    @XmlElement(name = "ATTRIBUTE")
    protected List<VODMLAttribute> attributes;
    @XmlElement(name = "COMPOSITION")
    protected List<VODMLComposition> compositions;
    @XmlElement(name = "REFERENCE")
    protected List<VODMLReference> references;
    /**
     * Can be used by references as identifier for an object or template.
     * 
     */
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Objects, i.e. ObjectType instances, can have a unique identifier which can be used in ORM-like references.
     * 
     * @return
     *     possible object is
     *     {@link VODMLObjectIdentifier }
     *     
     */
    public VODMLObjectIdentifier getPRIMARYKEY() {
        return primarykey;
    }

    /**
     * Sets the value of the primarykey property.
     * 
     * @param value
     *     allowed object is
     *     {@link VODMLObjectIdentifier }
     *     
     * @see #getPRIMARYKEY()
     */
    public void setPRIMARYKEY(VODMLObjectIdentifier value) {
        this.primarykey = value;
    }

    /**
     * Possible reference to a parent container of the object. May be given when the objects is not already
     *               contained in a colleciton on the parent object.
     *               Note, a VODMLReference can have multiple instances, but a CONTAINER MUST have only 1 instance.
     * 
     * @return
     *     possible object is
     *     {@link VODMLReference }
     *     
     */
    public VODMLReference getCONTAINER() {
        return container;
    }

    /**
     * Sets the value of the container property.
     * 
     * @param value
     *     allowed object is
     *     {@link VODMLReference }
     *     
     * @see #getCONTAINER()
     */
    public void setCONTAINER(VODMLReference value) {
        this.container = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getATTRIBUTES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VODMLAttribute }
     * </p>
     * 
     * 
     * @return
     *     The value of the attributes property.
     */
    public List<VODMLAttribute> getATTRIBUTES() {
        if (attributes == null) {
            attributes = new ArrayList<>();
        }
        return this.attributes;
    }

    /**
     * Gets the value of the compositions property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compositions property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCOMPOSITIONS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VODMLComposition }
     * </p>
     * 
     * 
     * @return
     *     The value of the compositions property.
     */
    public List<VODMLComposition> getCOMPOSITIONS() {
        if (compositions == null) {
            compositions = new ArrayList<>();
        }
        return this.compositions;
    }

    /**
     * Gets the value of the references property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the references property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getREFERENCES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VODMLReference }
     * </p>
     * 
     * 
     * @return
     *     The value of the references property.
     */
    public List<VODMLReference> getREFERENCES() {
        if (references == null) {
            references = new ArrayList<>();
        }
        return this.references;
    }

    /**
     * Can be used by references as identifier for an object or template.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getID()
     */
    public void setID(String value) {
        this.id = value;
    }

}
