//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:03 AM EDT 
//


package org.ivoa.votable_1_4.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VODMLRole complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VODMLRole">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="dmrole" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLRef" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLRole")
@XmlSeeAlso({
    VODMLAttribute.class,
    VODMLReference.class,
    VODMLComposition.class
})
public class VODMLRole {

    @XmlAttribute(name = "dmrole")
    protected String dmrole;

    /**
     * Gets the value of the dmrole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDmrole() {
        return dmrole;
    }

    /**
     * Sets the value of the dmrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDmrole(String value) {
        this.dmrole = value;
    }

}
