//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:03 AM EDT 
//


package org.ivoa.votable_1_4.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VODMLAttribute complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VODMLAttribute">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLRole">
 *       &lt;choice>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="COLUMN" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLFieldOrParamRef"/>
 *           &lt;element name="CONSTANT" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLFieldOrParamRef"/>
 *           &lt;element name="LITERAL" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLLiteral"/>
 *         &lt;/choice>
 *         &lt;element name="INSTANCE" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLObject" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLAttribute", propOrder = {
    "instances",
    "columnsAndCONSTANTSAndLITERALS"
})
public class VODMLAttribute
    extends VODMLRole
{

    @XmlElement(name = "INSTANCE")
    protected List<VODMLObject> instances;
    @XmlElementRefs({
        @XmlElementRef(name = "COLUMN", namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "LITERAL", namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CONSTANT", namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<? extends VODMLPrimitive>> columnsAndCONSTANTSAndLITERALS;

    /**
     * Gets the value of the instances property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instances property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getINSTANCES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VODMLObject }
     * 
     * 
     */
    public List<VODMLObject> getINSTANCES() {
        if (instances == null) {
            instances = new ArrayList<VODMLObject>();
        }
        return this.instances;
    }

    /**
     * Gets the value of the columnsAndCONSTANTSAndLITERALS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the columnsAndCONSTANTSAndLITERALS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCOLUMNSAndCONSTANTSAndLITERALS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link VODMLFieldOrParamRef }{@code >}
     * {@link JAXBElement }{@code <}{@link VODMLLiteral }{@code >}
     * {@link JAXBElement }{@code <}{@link VODMLFieldOrParamRef }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends VODMLPrimitive>> getCOLUMNSAndCONSTANTSAndLITERALS() {
        if (columnsAndCONSTANTSAndLITERALS == null) {
            columnsAndCONSTANTSAndLITERALS = new ArrayList<JAXBElement<? extends VODMLPrimitive>>();
        }
        return this.columnsAndCONSTANTSAndLITERALS;
    }

}
