//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.votable_1_4.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VODMLInstance complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="VODMLInstance">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <attribute name="dmtype" use="required" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLRef" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLInstance")
@XmlSeeAlso({
    VODMLObject.class,
    VODMLPrimitive.class
})
public abstract class VODMLInstance {

    @XmlAttribute(name = "dmtype", required = true)
    protected String dmtype;

    /**
     * Gets the value of the dmtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDmtype() {
        return dmtype;
    }

    /**
     * Sets the value of the dmtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDmtype(String value) {
        this.dmtype = value;
    }

}
