//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.votable_1_4.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A VODML element MUST have at least one model and at least on globals or templates.
 * 
 * <p>Java class for VODML complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="VODML">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="MODEL" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}Model" maxOccurs="unbounded"/>
 *         <choice maxOccurs="unbounded">
 *           <element name="GLOBALS" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLGlobals"/>
 *           <element name="TEMPLATES" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLInstanceTemplates"/>
 *         </choice>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODML", propOrder = {
    "models",
    "globalsAndTEMPLATES"
})
public class VODML {

    @XmlElement(name = "MODEL", required = true)
    protected List<Model> models;
    @XmlElements({
        @XmlElement(name = "GLOBALS", type = VODMLGlobals.class),
        @XmlElement(name = "TEMPLATES", type = VODMLInstanceTemplates.class)
    })
    protected List<Object> globalsAndTEMPLATES;

    /**
     * Gets the value of the models property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the models property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getMODELS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Model }
     * </p>
     * 
     * 
     * @return
     *     The value of the models property.
     */
    public List<Model> getMODELS() {
        if (models == null) {
            models = new ArrayList<>();
        }
        return this.models;
    }

    /**
     * Gets the value of the globalsAndTEMPLATES property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the globalsAndTEMPLATES property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getGLOBALSAndTEMPLATES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VODMLGlobals }
     * {@link VODMLInstanceTemplates }
     * </p>
     * 
     * 
     * @return
     *     The value of the globalsAndTEMPLATES property.
     */
    public List<Object> getGLOBALSAndTEMPLATES() {
        if (globalsAndTEMPLATES == null) {
            globalsAndTEMPLATES = new ArrayList<>();
        }
        return this.globalsAndTEMPLATES;
    }

}
