//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.votable_1_4.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VODMLRole complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="VODMLRole">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <attribute name="dmrole" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLRef" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLRole")
@XmlSeeAlso({
    VODMLAttribute.class,
    VODMLComposition.class,
    VODMLReference.class
})
public class VODMLRole {

    /**
     * NB: dmrole is optional (at the moment) *only* because VODMLObject::CONTAINER (a VODMLReferece) needs no role.
     *           ATTRIBUTE, COMPOSITION and REFERENCE MUST have a ROLE.
     *           Hard to model in XML schema, could be done in Schematron.
     * 
     */
    @XmlAttribute(name = "dmrole")
    protected String dmrole;

    /**
     * NB: dmrole is optional (at the moment) *only* because VODMLObject::CONTAINER (a VODMLReferece) needs no role.
     *           ATTRIBUTE, COMPOSITION and REFERENCE MUST have a ROLE.
     *           Hard to model in XML schema, could be done in Schematron.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDmrole() {
        return dmrole;
    }

    /**
     * Sets the value of the dmrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDmrole()
     */
    public void setDmrole(String value) {
        this.dmrole = value;
    }

}
