//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:03 AM EDT 
//


package org.ivoa.votable_1_4.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *       A VODML element MUST have at least one model and at least on globals or templates.
 *       
 * 
 * <p>Java class for VODML complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VODML">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MODEL" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}Model" maxOccurs="unbounded"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="GLOBALS" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLGlobals"/>
 *           &lt;element name="TEMPLATES" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLInstanceTemplates"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODML", propOrder = {
    "models",
    "globalsAndTEMPLATES"
})
public class VODML {

    @XmlElement(name = "MODEL", required = true)
    protected List<Model> models;
    @XmlElements({
        @XmlElement(name = "GLOBALS", type = VODMLGlobals.class),
        @XmlElement(name = "TEMPLATES", type = VODMLInstanceTemplates.class)
    })
    protected List<Object> globalsAndTEMPLATES;

    /**
     * Gets the value of the models property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the models property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMODELS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Model }
     * 
     * 
     */
    public List<Model> getMODELS() {
        if (models == null) {
            models = new ArrayList<Model>();
        }
        return this.models;
    }

    /**
     * Gets the value of the globalsAndTEMPLATES property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the globalsAndTEMPLATES property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGLOBALSAndTEMPLATES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VODMLGlobals }
     * {@link VODMLInstanceTemplates }
     * 
     * 
     */
    public List<Object> getGLOBALSAndTEMPLATES() {
        if (globalsAndTEMPLATES == null) {
            globalsAndTEMPLATES = new ArrayList<Object>();
        }
        return this.globalsAndTEMPLATES;
    }

}
