//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:03 AM EDT 
//


package org.ivoa.votable_1_4.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for VODMLObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VODMLObject">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLInstance">
 *       &lt;sequence>
 *         &lt;element name="PRIMARYKEY" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLObjectIdentifier" minOccurs="0"/>
 *         &lt;element name="CONTAINER" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLReference" minOccurs="0"/>
 *         &lt;element name="ATTRIBUTE" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLAttribute" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="COMPOSITION" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLComposition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="REFERENCE" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLReference" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLObject", propOrder = {
    "primarykey",
    "container",
    "attributes",
    "compositions",
    "references"
})
public class VODMLObject
    extends VODMLInstance
{

    @XmlElement(name = "PRIMARYKEY")
    protected VODMLObjectIdentifier primarykey;
    @XmlElement(name = "CONTAINER")
    protected VODMLReference container;
    @XmlElement(name = "ATTRIBUTE")
    protected List<VODMLAttribute> attributes;
    @XmlElement(name = "COMPOSITION")
    protected List<VODMLComposition> compositions;
    @XmlElement(name = "REFERENCE")
    protected List<VODMLReference> references;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the primarykey property.
     * 
     * @return
     *     possible object is
     *     {@link VODMLObjectIdentifier }
     *     
     */
    public VODMLObjectIdentifier getPRIMARYKEY() {
        return primarykey;
    }

    /**
     * Sets the value of the primarykey property.
     * 
     * @param value
     *     allowed object is
     *     {@link VODMLObjectIdentifier }
     *     
     */
    public void setPRIMARYKEY(VODMLObjectIdentifier value) {
        this.primarykey = value;
    }

    /**
     * Gets the value of the container property.
     * 
     * @return
     *     possible object is
     *     {@link VODMLReference }
     *     
     */
    public VODMLReference getCONTAINER() {
        return container;
    }

    /**
     * Sets the value of the container property.
     * 
     * @param value
     *     allowed object is
     *     {@link VODMLReference }
     *     
     */
    public void setCONTAINER(VODMLReference value) {
        this.container = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getATTRIBUTES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VODMLAttribute }
     * 
     * 
     */
    public List<VODMLAttribute> getATTRIBUTES() {
        if (attributes == null) {
            attributes = new ArrayList<VODMLAttribute>();
        }
        return this.attributes;
    }

    /**
     * Gets the value of the compositions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compositions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCOMPOSITIONS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VODMLComposition }
     * 
     * 
     */
    public List<VODMLComposition> getCOMPOSITIONS() {
        if (compositions == null) {
            compositions = new ArrayList<VODMLComposition>();
        }
        return this.compositions;
    }

    /**
     * Gets the value of the references property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the references property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getREFERENCES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VODMLReference }
     * 
     * 
     */
    public List<VODMLReference> getREFERENCES() {
        if (references == null) {
            references = new ArrayList<VODMLReference>();
        }
        return this.references;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
