//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.votable_1_4.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * This type allows a generic identifier to be assigned to an object. The identifier consists of one or more IDFIELD-s.
 * 				This way of identifying an object is equivalent to using one or more columns in a table as primary key.
 * 
 * <p>Java class for VODMLObjectIdentifier complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="VODMLObjectIdentifier">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="PKFIELD" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLObjectIdentifierField" maxOccurs="unbounded"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLObjectIdentifier", propOrder = {
    "pkfields"
})
@XmlSeeAlso({
    VODMLORMReference.class
})
public class VODMLObjectIdentifier {

    /**
     * A field in an identifier. The identifier may contain 1 or more such fields. Their order 
     * 						is important, ORM references to the object must use the same order for their foreign key.
     * 
     */
    @XmlElement(name = "PKFIELD", required = true)
    protected List<VODMLObjectIdentifierField> pkfields;

    /**
     * A field in an identifier. The identifier may contain 1 or more such fields. Their order 
     * 						is important, ORM references to the object must use the same order for their foreign key.
     * 
     * Gets the value of the pkfields property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pkfields property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getPKFIELDS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VODMLObjectIdentifierField }
     * </p>
     * 
     * 
     * @return
     *     The value of the pkfields property.
     */
    public List<VODMLObjectIdentifierField> getPKFIELDS() {
        if (pkfields == null) {
            pkfields = new ArrayList<>();
        }
        return this.pkfields;
    }

}
