//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.votable_1_4.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A VODMLCollection represents collection of child objects in a VO-DML Composition relationship.
 * 	    The collection receives the VO-DML ref to the composition relation, the member objects inside the 
 * 	    collection do *not* have a ROLE.
 * 	    
 * 
 * 
 *           a VODMLComposition MUST have a dmrole attribute, even though it is optional on VODMLRole
 * 
 * <p>Java class for VODMLComposition complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="VODMLComposition">
 *   <complexContent>
 *     <extension base="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLRole">
 *       <sequence>
 *         <element name="INSTANCE" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLObject" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="EXTINSTANCES" type="{http://www.w3.org/2001/XMLSchema}IDREF" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLComposition", propOrder = {
    "instances",
    "extinstances"
})
public class VODMLComposition
    extends VODMLRole
{

    /**
     * An object in the collection. It type must conform to the declared type of the VO-DML Collection.
     * 					    I.e. it must be that exact type or a sub-type.
     * 
     */
    @XmlElement(name = "INSTANCE")
    protected List<VODMLObject> instances;
    /**
     * Reference to an annotation of a a collection of objects that may contain child objects for this composition.
     *              This may be a GLOBALS or (a VODMLObject in )a TEMPLATES. 
     *              These object in general SHOULD have a CONTAINER pointer to the parent object.
     *              If they don't, then all objects in the collection are assumed to be children of the current parent object.
     *              NB we should add a consistency constraint on this.
     * 
     */
    @XmlElementRef(name = "EXTINSTANCES", namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", type = JAXBElement.class, required = false)
    protected List<JAXBElement<Object>> extinstances;

    /**
     * An object in the collection. It type must conform to the declared type of the VO-DML Collection.
     * 					    I.e. it must be that exact type or a sub-type.
     * 
     * Gets the value of the instances property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instances property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getINSTANCES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VODMLObject }
     * </p>
     * 
     * 
     * @return
     *     The value of the instances property.
     */
    public List<VODMLObject> getINSTANCES() {
        if (instances == null) {
            instances = new ArrayList<>();
        }
        return this.instances;
    }

    /**
     * Reference to an annotation of a a collection of objects that may contain child objects for this composition.
     *              This may be a GLOBALS or (a VODMLObject in )a TEMPLATES. 
     *              These object in general SHOULD have a CONTAINER pointer to the parent object.
     *              If they don't, then all objects in the collection are assumed to be children of the current parent object.
     *              NB we should add a consistency constraint on this.
     * 
     * Gets the value of the extinstances property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extinstances property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getEXTINSTANCES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * </p>
     * 
     * 
     * @return
     *     The value of the extinstances property.
     */
    public List<JAXBElement<Object>> getEXTINSTANCES() {
        if (extinstances == null) {
            extinstances = new ArrayList<>();
        }
        return this.extinstances;
    }

}
