//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:03 AM EDT 
//


package org.ivoa.votable_1_4.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Provides a reference to an ObjectType instance. Must allow that instance to be identified exactly.
 * 				Various different modes depending on how that instance is serialized.
 * 				- If as a Standalone instance in same VOTable document, an IDREF can point to its ID (use IDREF).
 * 				- If as a row in a TABLE a relational foreign key can be used (use ORMREFERENCE)
 * 				- if a remote document contains the serialized instance, a URI must be used that MUST be able to identify that object
 * 				inside its remote serialization (a REMOTEREFERENCE must be used).
 * 			
 * 
 * 
 *           a VODMLReference MUST have a dmrole attribute UNLESS it is used in a VODMLObject::CONTAINER, 
 *           even though it is optional on VODMLRole.
 *           
 * 
 * <p>Java class for VODMLReference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VODMLReference">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLRole">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="IDREF" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *           &lt;element name="REMOTEREFERENCE" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *           &lt;element name="FOREIGNKEY" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLORMReference"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLReference", propOrder = {
    "idrevesAndREMOTEREFERENCESAndFOREIGNKEIES"
})
public class VODMLReference
    extends VODMLRole
{

    @XmlElementRefs({
        @XmlElementRef(name = "FOREIGNKEY", namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "IDREF", namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "REMOTEREFERENCE", namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> idrevesAndREMOTEREFERENCESAndFOREIGNKEIES;

    /**
     * Gets the value of the idrevesAndREMOTEREFERENCESAndFOREIGNKEIES property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the idrevesAndREMOTEREFERENCESAndFOREIGNKEIES property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIDREVESAndREMOTEREFERENCESAndFOREIGNKEIES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link VODMLORMReference }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getIDREVESAndREMOTEREFERENCESAndFOREIGNKEIES() {
        if (idrevesAndREMOTEREFERENCESAndFOREIGNKEIES == null) {
            idrevesAndREMOTEREFERENCESAndFOREIGNKEIES = new ArrayList<JAXBElement<?>>();
        }
        return this.idrevesAndREMOTEREFERENCESAndFOREIGNKEIES;
    }

}
