//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:03 AM EDT 
//


package org.ivoa.votable_1_4.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VODMLPrimitive complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VODMLPrimitive">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLInstance">
 *       &lt;sequence>
 *         &lt;element name="OPTIONMAPPING" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLOptionMapping" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLPrimitive", propOrder = {
    "optionmappings"
})
@XmlSeeAlso({
    VODMLLiteral.class,
    VODMLFieldOrParamRef.class
})
public class VODMLPrimitive
    extends VODMLInstance
{

    @XmlElement(name = "OPTIONMAPPING")
    protected List<VODMLOptionMapping> optionmappings;

    /**
     * Gets the value of the optionmappings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the optionmappings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOPTIONMAPPINGS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VODMLOptionMapping }
     * 
     * 
     */
    public List<VODMLOptionMapping> getOPTIONMAPPINGS() {
        if (optionmappings == null) {
            optionmappings = new ArrayList<VODMLOptionMapping>();
        }
        return this.optionmappings;
    }

}
