//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:03 AM EDT 
//


package org.ivoa.votable_1_4.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				This type allows a generic identifier to be assigned to an object. The identifier consists of one or more IDFIELD-s.
 * 				This way of identifying an object is equivalent to using one or more columns in a table as primary key.
 * 			
 * 
 * <p>Java class for VODMLObjectIdentifier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VODMLObjectIdentifier">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PKFIELD" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLObjectIdentifierField" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLObjectIdentifier", propOrder = {
    "pkfields"
})
@XmlSeeAlso({
    VODMLORMReference.class
})
public class VODMLObjectIdentifier {

    @XmlElement(name = "PKFIELD", required = true)
    protected List<VODMLObjectIdentifierField> pkfields;

    /**
     * Gets the value of the pkfields property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pkfields property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPKFIELDS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VODMLObjectIdentifierField }
     * 
     * 
     */
    public List<VODMLObjectIdentifierField> getPKFIELDS() {
        if (pkfields == null) {
            pkfields = new ArrayList<VODMLObjectIdentifierField>();
        }
        return this.pkfields;
    }

}
