//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:03 AM EDT 
//


package org.ivoa.votable_1_4.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         A reference to an object identified by that object's identifier.
 *         The referenced object must be stored in a TABLE and must have been annotated with an explicit identifier.
 *       
 * 
 * <p>Java class for VODMLORMReference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VODMLORMReference">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLObjectIdentifier">
 *       &lt;sequence>
 *         &lt;element name="TARGETID" type="{http://www.w3.org/2001/XMLSchema}IDREF" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLORMReference", propOrder = {
    "targetid"
})
public class VODMLORMReference
    extends VODMLObjectIdentifier
{

    @XmlElement(name = "TARGETID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object targetid;

    /**
     * Gets the value of the targetid property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTARGETID() {
        return targetid;
    }

    /**
     * Sets the value of the targetid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTARGETID(Object value) {
        this.targetid = value;
    }

}
