//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.votable_1_4.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Allows one to map particular values defined in a VALUES/OPTION list to enumeration literals
 *     in the VO-DML model or to a concept in a SKOS vocabulary.
 * 
 * <p>Java class for VODMLOptionMapping complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="VODMLOptionMapping">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="MAPPEDOPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <choice>
 *           <element name="ENUMLITERAL" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLRef"/>
 *           <element name="SEMANTICCONCEPT" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         </choice>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLOptionMapping", propOrder = {
    "mappedoption",
    "semanticconcept",
    "enumliteral"
})
public class VODMLOptionMapping {

    /**
     * The VOTable OPTION value that is being mapped to enum literal or semantic concept.
     * 
     */
    @XmlElement(name = "MAPPEDOPTION", required = true)
    protected String mappedoption;
    /**
     * TBD anyURI as an identifier of concepts made sense for SKOS vocabularies. How about general semantic vocabularies?
     *             I.e. is it ok for the type be xs:string iso xs:anyURI?
     * 
     */
    @XmlElement(name = "SEMANTICCONCEPT")
    @XmlSchemaType(name = "anyURI")
    protected String semanticconcept;
    @XmlElement(name = "ENUMLITERAL")
    protected String enumliteral;

    /**
     * The VOTable OPTION value that is being mapped to enum literal or semantic concept.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAPPEDOPTION() {
        return mappedoption;
    }

    /**
     * Sets the value of the mappedoption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getMAPPEDOPTION()
     */
    public void setMAPPEDOPTION(String value) {
        this.mappedoption = value;
    }

    /**
     * TBD anyURI as an identifier of concepts made sense for SKOS vocabularies. How about general semantic vocabularies?
     *             I.e. is it ok for the type be xs:string iso xs:anyURI?
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEMANTICCONCEPT() {
        return semanticconcept;
    }

    /**
     * Sets the value of the semanticconcept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSEMANTICCONCEPT()
     */
    public void setSEMANTICCONCEPT(String value) {
        this.semanticconcept = value;
    }

    /**
     * Gets the value of the enumliteral property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENUMLITERAL() {
        return enumliteral;
    }

    /**
     * Sets the value of the enumliteral property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENUMLITERAL(String value) {
        this.enumliteral = value;
    }

}
