//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:03 AM EDT 
//


package org.ivoa.votable_1_4.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 	    A VODMLCollection represents collection of child objects in a VO-DML Composition relationship.
 * 	    The collection receives the VO-DML ref to the composition relation, the member objects inside the 
 * 	    collection do *not* have a ROLE.
 * 	    
 * 
 * 
 *           a VODMLComposition MUST have a dmrole attribute, even though it is optional on VODMLRole
 *           
 * 
 * <p>Java class for VODMLComposition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VODMLComposition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLRole">
 *       &lt;sequence>
 *         &lt;element name="INSTANCE" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLObject" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EXTINSTANCES" type="{http://www.w3.org/2001/XMLSchema}IDREF" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLComposition", propOrder = {
    "instances",
    "extinstances"
})
public class VODMLComposition
    extends VODMLRole
{

    @XmlElement(name = "INSTANCE")
    protected List<VODMLObject> instances;
    @XmlElementRef(name = "EXTINSTANCES", namespace = "http://www.ivoa.net/xml/VOTable/v1.4_vodml", type = JAXBElement.class, required = false)
    protected List<JAXBElement<Object>> extinstances;

    /**
     * Gets the value of the instances property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instances property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getINSTANCES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VODMLObject }
     * 
     * 
     */
    public List<VODMLObject> getINSTANCES() {
        if (instances == null) {
            instances = new ArrayList<VODMLObject>();
        }
        return this.instances;
    }

    /**
     * Gets the value of the extinstances property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extinstances property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEXTINSTANCES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * 
     */
    public List<JAXBElement<Object>> getEXTINSTANCES() {
        if (extinstances == null) {
            extinstances = new ArrayList<JAXBElement<Object>>();
        }
        return this.extinstances;
    }

}
