//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.votable_1_4.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VODMLObjectIdentifierField complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="VODMLObjectIdentifierField">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element name="LITERAL" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLLiteral"/>
 *         <element name="COLUMN" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLFieldOrParamRef"/>
 *         <element name="CONSTANT" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODMLFieldOrParamRef"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLObjectIdentifierField", propOrder = {
    "constant",
    "column",
    "literal"
})
public class VODMLObjectIdentifierField {

    @XmlElement(name = "CONSTANT")
    protected VODMLFieldOrParamRef constant;
    @XmlElement(name = "COLUMN")
    protected VODMLFieldOrParamRef column;
    @XmlElement(name = "LITERAL")
    protected VODMLLiteral literal;

    /**
     * Gets the value of the constant property.
     * 
     * @return
     *     possible object is
     *     {@link VODMLFieldOrParamRef }
     *     
     */
    public VODMLFieldOrParamRef getCONSTANT() {
        return constant;
    }

    /**
     * Sets the value of the constant property.
     * 
     * @param value
     *     allowed object is
     *     {@link VODMLFieldOrParamRef }
     *     
     */
    public void setCONSTANT(VODMLFieldOrParamRef value) {
        this.constant = value;
    }

    /**
     * Gets the value of the column property.
     * 
     * @return
     *     possible object is
     *     {@link VODMLFieldOrParamRef }
     *     
     */
    public VODMLFieldOrParamRef getCOLUMN() {
        return column;
    }

    /**
     * Sets the value of the column property.
     * 
     * @param value
     *     allowed object is
     *     {@link VODMLFieldOrParamRef }
     *     
     */
    public void setCOLUMN(VODMLFieldOrParamRef value) {
        this.column = value;
    }

    /**
     * Gets the value of the literal property.
     * 
     * @return
     *     possible object is
     *     {@link VODMLLiteral }
     *     
     */
    public VODMLLiteral getLITERAL() {
        return literal;
    }

    /**
     * Sets the value of the literal property.
     * 
     * @param value
     *     allowed object is
     *     {@link VODMLLiteral }
     *     
     */
    public void setLITERAL(VODMLLiteral value) {
        this.literal = value;
    }

}
