//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.votable_1_4.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="VODML" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}VODML" minOccurs="0"/>
 *         <element name="DESCRIPTION" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}anyTEXT" minOccurs="0"/>
 *         <element name="DEFINITIONS" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}Definitions" minOccurs="0"/>
 *         <choice maxOccurs="unbounded" minOccurs="0">
 *           <element name="COOSYS" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}CoordinateSystem"/>
 *           <element name="GROUP" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}Group"/>
 *           <element name="PARAM" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}Param"/>
 *           <element name="INFO" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}Info" maxOccurs="unbounded" minOccurs="0"/>
 *         </choice>
 *         <element name="RESOURCE" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}Resource" maxOccurs="unbounded"/>
 *         <element name="INFO" type="{http://www.ivoa.net/xml/VOTable/v1.4_vodml}Info" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       <attribute name="version">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             <enumeration value="1.3"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vodml",
    "description",
    "definitions",
    "coosysAndGROUPSAndPARAMS"
})
@XmlRootElement(name = "VOTABLE")
public class VOTABLE {

    @XmlElement(name = "VODML")
    protected VODML vodml;
    @XmlElement(name = "DESCRIPTION")
    protected AnyTEXT description;
    @XmlElement(name = "DEFINITIONS")
    protected Definitions definitions;
    @XmlElements({
        @XmlElement(name = "COOSYS", required = true, type = CoordinateSystem.class),
        @XmlElement(name = "GROUP", required = true, type = Group.class),
        @XmlElement(name = "PARAM", required = true, type = Param.class),
        @XmlElement(name = "INFO", required = true, type = Info.class),
        @XmlElement(name = "RESOURCE", required = true, type = Resource.class)
    })
    protected List<Object> coosysAndGROUPSAndPARAMS;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "version")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String version;

    /**
     * Gets the value of the vodml property.
     * 
     * @return
     *     possible object is
     *     {@link VODML }
     *     
     */
    public VODML getVODML() {
        return vodml;
    }

    /**
     * Sets the value of the vodml property.
     * 
     * @param value
     *     allowed object is
     *     {@link VODML }
     *     
     */
    public void setVODML(VODML value) {
        this.vodml = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link AnyTEXT }
     *     
     */
    public AnyTEXT getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyTEXT }
     *     
     */
    public void setDESCRIPTION(AnyTEXT value) {
        this.description = value;
    }

    /**
     * Gets the value of the definitions property.
     * 
     * @return
     *     possible object is
     *     {@link Definitions }
     *     
     */
    public Definitions getDEFINITIONS() {
        return definitions;
    }

    /**
     * Sets the value of the definitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definitions }
     *     
     */
    public void setDEFINITIONS(Definitions value) {
        this.definitions = value;
    }

    /**
     * Gets the value of the coosysAndGROUPSAndPARAMS property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coosysAndGROUPSAndPARAMS property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCOOSYSAndGROUPSAndPARAMS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoordinateSystem }
     * {@link Group }
     * {@link Info }
     * {@link Param }
     * {@link Resource }
     * </p>
     * 
     * 
     * @return
     *     The value of the coosysAndGROUPSAndPARAMS property.
     */
    public List<Object> getCOOSYSAndGROUPSAndPARAMS() {
        if (coosysAndGROUPSAndPARAMS == null) {
            coosysAndGROUPSAndPARAMS = new ArrayList<>();
        }
        return this.coosysAndGROUPSAndPARAMS;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
