//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:02 AM EDT 
//


package org.ivoa.vodml.mapping.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModelMapping complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModelMapping">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="file" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="java-package" type="{http://volute.g-vo.org/dm/vo-dml-mapping/v0.9}JavaName" minOccurs="0"/>
 *         &lt;element name="xml-targetnamespace" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="xsd-schemalocation" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="type-mapping" type="{http://volute.g-vo.org/dm/vo-dml-mapping/v0.9}TypeMapping" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelMapping", propOrder = {
    "name",
    "file",
    "url",
    "javaPackage",
    "xmlTargetnamespace",
    "xsdSchemalocation",
    "typeMapping"
})
public class ModelMapping {

    @XmlElement(required = true)
    protected String name;
    protected String file;
    @XmlSchemaType(name = "anyURI")
    protected String url;
    @XmlElement(name = "java-package")
    protected String javaPackage;
    @XmlElement(name = "xml-targetnamespace")
    @XmlSchemaType(name = "anyURI")
    protected String xmlTargetnamespace;
    @XmlElement(name = "xsd-schemalocation")
    @XmlSchemaType(name = "anyURI")
    protected String xsdSchemalocation;
    @XmlElement(name = "type-mapping")
    protected List<TypeMapping> typeMapping;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFile(String value) {
        this.file = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the javaPackage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavaPackage() {
        return javaPackage;
    }

    /**
     * Sets the value of the javaPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavaPackage(String value) {
        this.javaPackage = value;
    }

    /**
     * Gets the value of the xmlTargetnamespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlTargetnamespace() {
        return xmlTargetnamespace;
    }

    /**
     * Sets the value of the xmlTargetnamespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlTargetnamespace(String value) {
        this.xmlTargetnamespace = value;
    }

    /**
     * Gets the value of the xsdSchemalocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsdSchemalocation() {
        return xsdSchemalocation;
    }

    /**
     * Sets the value of the xsdSchemalocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsdSchemalocation(String value) {
        this.xsdSchemalocation = value;
    }

    /**
     * Gets the value of the typeMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeMapping }
     * 
     * 
     */
    public List<TypeMapping> getTypeMapping() {
        if (typeMapping == null) {
            typeMapping = new ArrayList<TypeMapping>();
        }
        return this.typeMapping;
    }

}
