//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:02 AM EDT 
//


package org.ivoa.vodml.mapping.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ivoa.vodml.mapping.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MappedModels_QNAME = new QName("http://volute.g-vo.org/dm/vo-dml-mapping/v0.9", "mappedModels");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ivoa.vodml.mapping.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MappedModels }
     * 
     */
    public MappedModels createMappedModels() {
        return new MappedModels();
    }

    /**
     * Create an instance of {@link TypeMapping }
     * 
     */
    public TypeMapping createTypeMapping() {
        return new TypeMapping();
    }

    /**
     * Create an instance of {@link ModelMapping }
     * 
     */
    public ModelMapping createModelMapping() {
        return new ModelMapping();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MappedModels }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://volute.g-vo.org/dm/vo-dml-mapping/v0.9", name = "mappedModels")
    public JAXBElement<MappedModels> createMappedModels(MappedModels value) {
        return new JAXBElement<MappedModels>(_MappedModels_QNAME, MappedModels.class, null, value);
    }

}
