//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.mapping.jaxb;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ivoa.vodml.mapping.jaxb package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _MappedModels_QNAME = new QName("http://volute.g-vo.org/dm/vo-dml-mapping/v0.9", "mappedModels");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ivoa.vodml.mapping.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MappedModels }
     * 
     * @return
     *     the new instance of {@link MappedModels }
     */
    public MappedModels createMappedModels() {
        return new MappedModels();
    }

    /**
     * Create an instance of {@link ModelMapping }
     * 
     * @return
     *     the new instance of {@link ModelMapping }
     */
    public ModelMapping createModelMapping() {
        return new ModelMapping();
    }

    /**
     * Create an instance of {@link TypeMapping }
     * 
     * @return
     *     the new instance of {@link TypeMapping }
     */
    public TypeMapping createTypeMapping() {
        return new TypeMapping();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MappedModels }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MappedModels }{@code >}
     */
    @XmlElementDecl(namespace = "http://volute.g-vo.org/dm/vo-dml-mapping/v0.9", name = "mappedModels")
    public JAXBElement<MappedModels> createMappedModels(MappedModels value) {
        return new JAXBElement<>(_MappedModels_QNAME, MappedModels.class, null, value);
    }

}
