//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:02 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://volute.g-vo.org/dm/vo-dml-mapping/v0.9")
package org.ivoa.vodml.mapping.jaxb;
