//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:02 AM EDT 
//


package org.ivoa.vodml.mapping.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeMapping complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypeMapping">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vodml-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="java-type" type="{http://volute.g-vo.org/dm/vo-dml-mapping/v0.9}JavaName" minOccurs="0"/>
 *         &lt;element name="xsd-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypeMapping", propOrder = {
    "vodmlId",
    "javaType",
    "xsdType"
})
public class TypeMapping {

    @XmlElement(name = "vodml-id", required = true)
    protected String vodmlId;
    @XmlElement(name = "java-type")
    protected String javaType;
    @XmlElement(name = "xsd-type")
    protected String xsdType;

    /**
     * Gets the value of the vodmlId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVodmlId() {
        return vodmlId;
    }

    /**
     * Sets the value of the vodmlId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVodmlId(String value) {
        this.vodmlId = value;
    }

    /**
     * Gets the value of the javaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavaType() {
        return javaType;
    }

    /**
     * Sets the value of the javaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavaType(String value) {
        this.javaType = value;
    }

    /**
     * Gets the value of the xsdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsdType() {
        return xsdType;
    }

    /**
     * Sets the value of the xsdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsdType(String value) {
        this.xsdType = value;
    }

}
