//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.mapping.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeMapping complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="TypeMapping">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="vodml-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="java-type" type="{http://volute.g-vo.org/dm/vo-dml-mapping/v0.9}JavaName" minOccurs="0"/>
 *         <element name="xsd-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypeMapping", propOrder = {
    "vodmlId",
    "javaType",
    "xsdType"
})
public class TypeMapping {

    @XmlElement(name = "vodml-id", required = true)
    protected String vodmlId;
    @XmlElement(name = "java-type")
    protected String javaType;
    /**
     * Maps to XSD predefined type such as xsd:string etc.
     *         SHould NOT have 'xsd' or 'xs' prefix, this must be supplied by generator.
     * 
     */
    @XmlElement(name = "xsd-type")
    protected String xsdType;

    /**
     * Gets the value of the vodmlId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVodmlId() {
        return vodmlId;
    }

    /**
     * Sets the value of the vodmlId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVodmlId(String value) {
        this.vodmlId = value;
    }

    /**
     * Gets the value of the javaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavaType() {
        return javaType;
    }

    /**
     * Sets the value of the javaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavaType(String value) {
        this.javaType = value;
    }

    /**
     * Maps to XSD predefined type such as xsd:string etc.
     *         SHould NOT have 'xsd' or 'xs' prefix, this must be supplied by generator.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsdType() {
        return xsdType;
    }

    /**
     * Sets the value of the xsdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getXsdType()
     */
    public void setXsdType(String value) {
        this.xsdType = value;
    }

}
