//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Must refer to a ValueType.
 * 
 * <p>Java class for Attribute complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Attribute">
 *   <complexContent>
 *     <extension base="{http://www.ivoa.net/xml/VODML/v1}Role">
 *       <sequence>
 *         <element name="semanticconcept" type="{http://www.ivoa.net/xml/VODML/v1}SemanticConcept" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Attribute", propOrder = {
    "semanticconcept"
})
public class Attribute
    extends Role
{

    /**
     * It is possible to assign a SemanticConcept to an attribute definition.
     *                 This means that the values of the attribute have to comply with the definition of the 
     *                 SemanticConcept.
     *                 This can be done in two manners. Either the SemanticConcept
     *                 gives a link to a semantic vocabulary, in which case the value must be a
     *                 concept defined in that vocabulary.
     *                 Or it defines a topConcept, in which case the value must be a  concept that is explicitly
     *                 declared to be (narrower than)
     *                 that concept, or a concept that is narrower than that concept.
     *                 FOr details on the interpretation see the VO-DML document.
     * 
     */
    protected SemanticConcept semanticconcept;

    /**
     * It is possible to assign a SemanticConcept to an attribute definition.
     *                 This means that the values of the attribute have to comply with the definition of the 
     *                 SemanticConcept.
     *                 This can be done in two manners. Either the SemanticConcept
     *                 gives a link to a semantic vocabulary, in which case the value must be a
     *                 concept defined in that vocabulary.
     *                 Or it defines a topConcept, in which case the value must be a  concept that is explicitly
     *                 declared to be (narrower than)
     *                 that concept, or a concept that is narrower than that concept.
     *                 FOr details on the interpretation see the VO-DML document.
     * 
     * @return
     *     possible object is
     *     {@link SemanticConcept }
     *     
     */
    public SemanticConcept getSemanticconcept() {
        return semanticconcept;
    }

    /**
     * Sets the value of the semanticconcept property.
     * 
     * @param value
     *     allowed object is
     *     {@link SemanticConcept }
     *     
     * @see #getSemanticconcept()
     */
    public void setSemanticconcept(SemanticConcept value) {
        this.semanticconcept = value;
    }

}
