//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:06 AM EDT 
//


package org.ivoa.vodml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *           This type implements a composition relation between the parent and child ObjectTypes.
 *           Its instances are ONLY used to set the composition field on an ObjectType.
 *           It is a rule that an object type can only be the target of a single composition definition.
 *           A subclass can be assigned a target to a composition if a
 *         baseclass is already assigned such a target, but only if the composition is explicitly 'subsetted'.
 *         A composition is assumed to be a set, i.e.
 *         a given object (as identified by its identifier!) cannot occur
 *         multiple times in the composition.
 *         The composition
 *         may be ordered, which implies that the order in which objects have been added
 *         to
 *         the parent is to be preserved. As clients can always do an explicit sort on any of the child objects' attributes,
 *         it seems not necessary to add functionality for
 *         declaring a composition is
 *         sorted on one or more attributes.
 *         Through the uniqueInCollection constraint that can be assigned to attributes, a composition can impose the
 *         constraint that different objects in the composition
 *         must have distinct values of the
 *         attribute to which that constraint is assigned.
 *         It would be better probably to add the capability to assign such constraints to this composition type.
 *         This would
 *         also give more flexibility in for example creating explicit (named) keys, or defining
 *         multi-attribute uniqueness constraints.
 *       
 * 
 * <p>Java class for Composition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Composition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/VODML/v1}Relation">
 *       &lt;sequence>
 *         &lt;element name="isOrdered" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Composition", propOrder = {
    "isOrdered"
})
public class Composition
    extends Relation
{

    @XmlElement(defaultValue = "false")
    protected Boolean isOrdered;

    /**
     * Gets the value of the isOrdered property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsOrdered() {
        return isOrdered;
    }

    /**
     * Sets the value of the isOrdered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsOrdered(Boolean value) {
        this.isOrdered = value;
    }

}
