//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Constraint represents rules that instances of Type-s must obey to be valid.  
 *       A generic Constraint only has a 'description' element 
 *       which describes the constraint in English.
 *       In future versions of the language extra elements may be added that give a more formal
 *       definition of the constraint. In particular we may add expressions in a language
 *       such as OCL or subset thereof tuned to VO-DML.
 *       In terms of OCL, VO-DML COnstraint-s are invariants of a Type.
 * 
 * <p>Java class for Constraint complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Constraint">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Constraint", propOrder = {
    "description"
})
@XmlSeeAlso({
    SubsettedRole.class
})
public class Constraint {

    /**
     * A natural language description of the constraint.
     * 
     */
    protected String description;

    /**
     * A natural language description of the constraint.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDescription()
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
