//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:06 AM EDT 
//


package org.ivoa.vodml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         This type represents how to reference a ReferencableElement.
 *         It can serve as base class to those types that explicitly reference another type, such as relations and roles.
 *         It provides for a uniform way to represent the reference to
 *         the target element using the 'utyperef' element.
 *         An important design choice is that we wish to allow references to elements in remote models.
 *         For that reasons we can not use an ID/IDREF or key/keyref pattern.
 *         Instead we define various constraints on
 *         this type and its usage in various contexts using
 *         the Schematron file in vo-dml.sch.xml.
 *       
 * 
 * <p>Java class for ElementRef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ElementRef">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vodml-ref" type="{http://www.ivoa.net/xml/VODML/v1}VODMLREF"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElementRef", propOrder = {
    "vodmlRef"
})
public class ElementRef {

    @XmlElement(name = "vodml-ref", required = true)
    protected String vodmlRef;

    /**
     * Gets the value of the vodmlRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVodmlRef() {
        return vodmlRef;
    }

    /**
     * Sets the value of the vodmlRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVodmlRef(String value) {
        this.vodmlRef = value;
    }

}
