//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * This type represents how to reference a ReferencableElement.
 *         It can serve as base class to those types that explicitly reference another type, such as relations and roles.
 *         It provides for a uniform way to represent the reference to
 *         the target element using the 'utyperef' element.
 *         An important design choice is that we wish to allow references to elements in remote models.
 *         For that reasons we can not use an ID/IDREF or key/keyref pattern.
 *         Instead we define various constraints on
 *         this type and its usage in various contexts using
 *         the Schematron file in vo-dml.sch.xml.
 * 
 * <p>Java class for ElementRef complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ElementRef">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="vodml-ref" type="{http://www.ivoa.net/xml/VODML/v1}VODMLREF"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElementRef", propOrder = {
    "vodmlRef"
})
public class ElementRef {

    /**
     * The element identifying the referenced target element.
     *             See the documentation for the VODMLREF type.
     * 
     */
    @XmlElement(name = "vodml-ref", required = true)
    protected String vodmlRef;

    /**
     * The element identifying the referenced target element.
     *             See the documentation for the VODMLREF type.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVodmlRef() {
        return vodmlRef;
    }

    /**
     * Sets the value of the vodmlRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getVodmlRef()
     */
    public void setVodmlRef(String value) {
        this.vodmlRef = value;
    }

}
