//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:06 AM EDT 
//


package org.ivoa.vodml.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         A primitive type with a limited, discrete set of values.
 *         May explicitly extend a PrimitiveType. Its values must be compatible with that type then.
 *         TBD Should define what it
 *         might mean for an enumeraiton to extend another enumeration.
 *         Should it restrict the possible values further? Or should it add to the values? Or ...?
 *       
 * 
 * <p>Java class for Enumeration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Enumeration">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/VODML/v1}PrimitiveType">
 *       &lt;sequence>
 *         &lt;element name="literal" type="{http://www.ivoa.net/xml/VODML/v1}EnumLiteral" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Enumeration", propOrder = {
    "literal"
})
public class Enumeration
    extends PrimitiveType
{

    @XmlElement(required = true)
    protected List<EnumLiteral> literal;

    /**
     * Gets the value of the literal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the literal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLiteral().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnumLiteral }
     * 
     * 
     */
    public List<EnumLiteral> getLiteral() {
        if (literal == null) {
            literal = new ArrayList<EnumLiteral>();
        }
        return this.literal;
    }

}
