//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A primitive type with a limited, discrete set of values.
 *         May explicitly extend a PrimitiveType. Its values must be compatible with that type then.
 *         TBD Should define what it
 *         might mean for an enumeraiton to extend another enumeration.
 *         Should it restrict the possible values further? Or should it add to the values? Or ...?
 * 
 * <p>Java class for Enumeration complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Enumeration">
 *   <complexContent>
 *     <extension base="{http://www.ivoa.net/xml/VODML/v1}PrimitiveType">
 *       <sequence>
 *         <element name="literal" type="{http://www.ivoa.net/xml/VODML/v1}EnumLiteral" maxOccurs="unbounded"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Enumeration", propOrder = {
    "literal"
})
public class Enumeration
    extends PrimitiveType
{

    /**
     * TODO
     * 
     */
    @XmlElement(required = true)
    protected List<EnumLiteral> literal;

    /**
     * TODO
     * 
     * Gets the value of the literal property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the literal property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getLiteral().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnumLiteral }
     * </p>
     * 
     * 
     * @return
     *     The value of the literal property.
     */
    public List<EnumLiteral> getLiteral() {
        if (literal == null) {
            literal = new ArrayList<>();
        }
        return this.literal;
    }

}
