//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A "proxy" for an external model that is being used by the current model. 
 *         Defines the url where the VO-DML representation of that model can be retrieved, and
 *         replicates its name that MUST be used when making references to
 *         elements in that model using a VODMLREF element.
 * 
 * <p>Java class for ModelImport complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ModelImport">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="name" type="{http://www.ivoa.net/xml/VODML/v1}ModelName"/>
 *         <element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         <element name="documentationURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelImport", propOrder = {
    "name",
    "identifier",
    "version",
    "url",
    "documentationURL"
})
public class ModelImport {

    /**
     * Name by which imported model is used in the current model and its documentation.
     *                     This name MUST be the same as the 'name' of the model definition in that remote document.
     *                     For all utypes pointing to elements in the imported model MUST use this name as prefix.
     * 
     */
    @XmlElement(required = true)
    protected String name;
    /**
     * A string holding the identifier by which the imported model is registered in an 
     *                         IVOA compatible registry. Must be the same value as the 'identifier' of the imported model.
     * 
     */
    protected String identifier;
    /**
     * Version of the imported model.
     * 
     */
    protected String version;
    /**
     * URL from which the VO-DML model document can be downloaded.
     *             Note, could likely be done through a registry once ivoId is known.
     *             TBD SHOULD this be a generic URI, or can we insits on URL?
     * 
     */
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String url;
    /**
     * URL where a documentation HTML file for the remote model can be downloaded.
     *             This SHOULD be a document that contains anchors for each element thta has as name attribute the vodml-id of that element.
     *             I.e. it is assumed that the
     *             vodml-id-s of the imported types can be added onto this documentationURL
     *             (should end with a #?) so that a direct link to the documentation for a referenced data model element can be found.
     * 
     */
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String documentationURL;

    /**
     * Name by which imported model is used in the current model and its documentation.
     *                     This name MUST be the same as the 'name' of the model definition in that remote document.
     *                     For all utypes pointing to elements in the imported model MUST use this name as prefix.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getName()
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * A string holding the identifier by which the imported model is registered in an 
     *                         IVOA compatible registry. Must be the same value as the 'identifier' of the imported model.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getIdentifier()
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Version of the imported model.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getVersion()
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * URL from which the VO-DML model document can be downloaded.
     *             Note, could likely be done through a registry once ivoId is known.
     *             TBD SHOULD this be a generic URI, or can we insits on URL?
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getUrl()
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * URL where a documentation HTML file for the remote model can be downloaded.
     *             This SHOULD be a document that contains anchors for each element thta has as name attribute the vodml-id of that element.
     *             I.e. it is assumed that the
     *             vodml-id-s of the imported types can be added onto this documentationURL
     *             (should end with a #?) so that a direct link to the documentation for a referenced data model element can be found.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentationURL() {
        return documentationURL;
    }

    /**
     * Sets the value of the documentationURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDocumentationURL()
     */
    public void setDocumentationURL(String value) {
        this.documentationURL = value;
    }

}
