//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.jaxb;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Also called "Cardinality". Indicates how many instances of a datatype can/must be associated to a given role.
 *         Unless
 *         Follows model in XSD, i.e. with explicit lower bound and upper bound on number of instances.
 *         maxOccurs must be gte minOccurs, unless it is negative, in which case it corresponds to unbounded.
 * 
 * <p>Java class for Multiplicity complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Multiplicity">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <choice>
 *           <element name="minOccurs" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         </choice>
 *         <element name="maxOccurs" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Multiplicity", propOrder = {
    "minOccurs",
    "maxOccurs"
})
public class Multiplicity {

    /**
     * Lower bound on number of instances/values.
     * 
     */
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger minOccurs;
    /**
     * When negative, unbounded.
     * 
     */
    protected int maxOccurs;

    /**
     * Lower bound on number of instances/values.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinOccurs() {
        return minOccurs;
    }

    /**
     * Sets the value of the minOccurs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getMinOccurs()
     */
    public void setMinOccurs(BigInteger value) {
        this.minOccurs = value;
    }

    /**
     * When negative, unbounded.
     * 
     */
    public int getMaxOccurs() {
        return maxOccurs;
    }

    /**
     * Sets the value of the maxOccurs property.
     * 
     */
    public void setMaxOccurs(int value) {
        this.maxOccurs = value;
    }

}
