//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.jaxb;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ivoa.vodml.jaxb package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Model_QNAME = new QName("http://www.ivoa.net/xml/VODML/v1", "model");
    private static final QName _Models_QNAME = new QName("http://www.ivoa.net/xml/VODML/v1", "models");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ivoa.vodml.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Models }
     * 
     * @return
     *     the new instance of {@link Models }
     */
    public Models createModels() {
        return new Models();
    }

    /**
     * Create an instance of {@link Model }
     * 
     * @return
     *     the new instance of {@link Model }
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link ElementRef }
     * 
     * @return
     *     the new instance of {@link ElementRef }
     */
    public ElementRef createElementRef() {
        return new ElementRef();
    }

    /**
     * Create an instance of {@link ModelImport }
     * 
     * @return
     *     the new instance of {@link ModelImport }
     */
    public ModelImport createModelImport() {
        return new ModelImport();
    }

    /**
     * Create an instance of {@link Package }
     * 
     * @return
     *     the new instance of {@link Package }
     */
    public Package createPackage() {
        return new Package();
    }

    /**
     * Create an instance of {@link ObjectType }
     * 
     * @return
     *     the new instance of {@link ObjectType }
     */
    public ObjectType createObjectType() {
        return new ObjectType();
    }

    /**
     * Create an instance of {@link PrimitiveType }
     * 
     * @return
     *     the new instance of {@link PrimitiveType }
     */
    public PrimitiveType createPrimitiveType() {
        return new PrimitiveType();
    }

    /**
     * Create an instance of {@link DataType }
     * 
     * @return
     *     the new instance of {@link DataType }
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link Enumeration }
     * 
     * @return
     *     the new instance of {@link Enumeration }
     */
    public Enumeration createEnumeration() {
        return new Enumeration();
    }

    /**
     * Create an instance of {@link EnumLiteral }
     * 
     * @return
     *     the new instance of {@link EnumLiteral }
     */
    public EnumLiteral createEnumLiteral() {
        return new EnumLiteral();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     * @return
     *     the new instance of {@link Attribute }
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link SemanticConcept }
     * 
     * @return
     *     the new instance of {@link SemanticConcept }
     */
    public SemanticConcept createSemanticConcept() {
        return new SemanticConcept();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     * @return
     *     the new instance of {@link Reference }
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link Composition }
     * 
     * @return
     *     the new instance of {@link Composition }
     */
    public Composition createComposition() {
        return new Composition();
    }

    /**
     * Create an instance of {@link Multiplicity }
     * 
     * @return
     *     the new instance of {@link Multiplicity }
     */
    public Multiplicity createMultiplicity() {
        return new Multiplicity();
    }

    /**
     * Create an instance of {@link Constraint }
     * 
     * @return
     *     the new instance of {@link Constraint }
     */
    public Constraint createConstraint() {
        return new Constraint();
    }

    /**
     * Create an instance of {@link SubsettedRole }
     * 
     * @return
     *     the new instance of {@link SubsettedRole }
     */
    public SubsettedRole createSubsettedRole() {
        return new SubsettedRole();
    }

    /**
     * Create an instance of {@link Models.Modellocation }
     * 
     * @return
     *     the new instance of {@link Models.Modellocation }
     */
    public Models.Modellocation createModelsModellocation() {
        return new Models.Modellocation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Model }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Model }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/VODML/v1", name = "model")
    public JAXBElement<Model> createModel(Model value) {
        return new JAXBElement<>(_Model_QNAME, Model.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Models }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Models }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/VODML/v1", name = "models")
    public JAXBElement<Models> createModels(Models value) {
        return new JAXBElement<>(_Models_QNAME, Models.class, null, value);
    }

}
