//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A Package is a container for type definitions and possible (child-)packages.
 *                 Names of types only need to be unique within their container (model or package),
 *                 hence a package provides further name-spacing for type definitions.
 *                 When
 *                 deriving physical representations of a model, packages may be mapped to containers in the target
 *                 meta-model.
 *                 For example in mapping to XSD they may give rise to separate documents with type definitions and their
 *                 own targetNamespace. When generating
 *                 Java classes they may be used to define seprate packages for
 *                 the classes derived form the types.
 *             
 * 
 * 
 *                         Name of the package is constrained in that
 *                         there can only be one package with a given name
 *                         in the container in which the package is defined, i.e. the model or a parent package.
 *                         TBD we may wish to extend this rule to all children
 *                         defined in a container, including types.
 * 
 * <p>Java class for Package complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Package">
 *   <complexContent>
 *     <extension base="{http://www.ivoa.net/xml/VODML/v1}ReferableElement">
 *       <sequence>
 *         <element name="primitiveType" type="{http://www.ivoa.net/xml/VODML/v1}PrimitiveType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="enumeration" type="{http://www.ivoa.net/xml/VODML/v1}Enumeration" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="dataType" type="{http://www.ivoa.net/xml/VODML/v1}DataType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="objectType" type="{http://www.ivoa.net/xml/VODML/v1}ObjectType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="package" type="{http://www.ivoa.net/xml/VODML/v1}Package" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Package", propOrder = {
    "primitiveType",
    "enumeration",
    "dataType",
    "objectType",
    "_package"
})
public class Package
    extends ReferableElement
{

    /**
     * Collection of PrimitiveType-s defined in this package.
     * 
     */
    protected List<PrimitiveType> primitiveType;
    /**
     * Collection of Enumeration-s defined in this package.
     * 
     */
    protected List<Enumeration> enumeration;
    /**
     * Collection of DataType-s defined in this package.
     * 
     */
    protected List<DataType> dataType;
    /**
     * Collection of ObjectType-s defined in this package.
     * 
     */
    protected List<ObjectType> objectType;
    /**
     * Collection of child Package-s defined in this package.
     * 
     */
    @XmlElement(name = "package")
    protected List<Package> _package;

    /**
     * Collection of PrimitiveType-s defined in this package.
     * 
     * Gets the value of the primitiveType property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the primitiveType property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getPrimitiveType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrimitiveType }
     * </p>
     * 
     * 
     * @return
     *     The value of the primitiveType property.
     */
    public List<PrimitiveType> getPrimitiveType() {
        if (primitiveType == null) {
            primitiveType = new ArrayList<>();
        }
        return this.primitiveType;
    }

    /**
     * Collection of Enumeration-s defined in this package.
     * 
     * Gets the value of the enumeration property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enumeration property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getEnumeration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Enumeration }
     * </p>
     * 
     * 
     * @return
     *     The value of the enumeration property.
     */
    public List<Enumeration> getEnumeration() {
        if (enumeration == null) {
            enumeration = new ArrayList<>();
        }
        return this.enumeration;
    }

    /**
     * Collection of DataType-s defined in this package.
     * 
     * Gets the value of the dataType property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataType property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getDataType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataType }
     * </p>
     * 
     * 
     * @return
     *     The value of the dataType property.
     */
    public List<DataType> getDataType() {
        if (dataType == null) {
            dataType = new ArrayList<>();
        }
        return this.dataType;
    }

    /**
     * Collection of ObjectType-s defined in this package.
     * 
     * Gets the value of the objectType property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objectType property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getObjectType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectType }
     * </p>
     * 
     * 
     * @return
     *     The value of the objectType property.
     */
    public List<ObjectType> getObjectType() {
        if (objectType == null) {
            objectType = new ArrayList<>();
        }
        return this.objectType;
    }

    /**
     * Collection of child Package-s defined in this package.
     * 
     * Gets the value of the package property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the package property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getPackage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Package }
     * </p>
     * 
     * 
     * @return
     *     The value of the package property.
     */
    public List<Package> getPackage() {
        if (_package == null) {
            _package = new ArrayList<>();
        }
        return this._package;
    }

}
