//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Atomic/simple type. Defined by a single value. Generally a built in type from the IVOA profile model,
 *         or a subclass of one of those types.
 * 
 * <p>Java class for PrimitiveType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="PrimitiveType">
 *   <complexContent>
 *     <extension base="{http://www.ivoa.net/xml/VODML/v1}ValueType">
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrimitiveType")
@XmlSeeAlso({
    Enumeration.class
})
public class PrimitiveType
    extends ValueType
{


}
