//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * This is the base type for all types whose elements can be explicitly referenced.
 *         To this end it has a 'vodml-id' element of type VODMLID that allows explicit and unique identification of 
 *         these elements within the context of the model.
 *         Generally these are also elements that can be
 *         represented explicitly in alternative serialisations of
 *         a data model, such as a VOTable or a relational model.
 *         These should use the value of the utype element to "point into a data model" and identify a
 *         model element. VO-DML itself also has needs of pointing to other elements, sometimes in another model.
 *         The VODMLREF type is used for such references, which will always be named 'vodml-ref'.
 * 
 * <p>Java class for ReferableElement complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ReferableElement">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="vodml-id" type="{http://www.ivoa.net/xml/VODML/v1}VODMLID"/>
 *         <element name="name" type="{http://www.ivoa.net/xml/VODML/v1}VODMLName"/>
 *         <element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferableElement", propOrder = {
    "vodmlId",
    "name",
    "description"
})
@XmlSeeAlso({
    Package.class,
    Type.class,
    EnumLiteral.class,
    Role.class
})
public abstract class ReferableElement {

    /**
     * Identifier for its containing element.
     *               Extracted as a separate type so that we can easily adapt to a different identifier design.
     * 
     */
    @XmlElement(name = "vodml-id", required = true)
    protected String vodmlId;
    /**
     * The name of the model element. 
     *             MUST NOT be an empty string.
     * 
     */
    @XmlElement(required = true)
    protected String name;
    /**
     * Human readable description of the model element.
     * 
     */
    protected String description;
    /**
     * A referencable element may be given an @id attribute to reflect an identifier
     *           defined in some source document form which a VO-DML model may have been derived.
     * 
     */
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Identifier for its containing element.
     *               Extracted as a separate type so that we can easily adapt to a different identifier design.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVodmlId() {
        return vodmlId;
    }

    /**
     * Sets the value of the vodmlId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getVodmlId()
     */
    public void setVodmlId(String value) {
        this.vodmlId = value;
    }

    /**
     * The name of the model element. 
     *             MUST NOT be an empty string.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getName()
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Human readable description of the model element.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDescription()
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * A referencable element may be given an @id attribute to reflect an identifier
     *           defined in some source document form which a VO-DML model may have been derived.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getId()
     */
    public void setId(String value) {
        this.id = value;
    }

}
