//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A Reference is a Relation that indicates a kind of "usage" relationship
 *         between the target ObjectType and the owner of the reference, the "referrer".
 *         The referrer can be an ObjectType (typically) but also a DataType.
 *         The relation is
 *         looser than the composition relationship, acting like a
 *         semantically meaningful pointer rather than indicating a component of the referrer.
 *         Consequently, in general many referrers can point at the same target instance,
 *         and ObjectType-s can
 *         be the target in different reference definitions.
 *         The lifecycle of the target is not bound to that of the referrer.
 *         Often the target instance is used to provide a context for the definition of
 *         the referrer. For example a coordinate frame may be
 *         referenced to provide context to coordinate values.
 *         TBD more needed ...?
 *       
 * 
 * 
 *             TBD Should have multiplicity 0..1 or 1?
 * 
 * <p>Java class for Reference complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Reference">
 *   <complexContent>
 *     <extension base="{http://www.ivoa.net/xml/VODML/v1}Relation">
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reference")
public class Reference
    extends Relation
{


}
