//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Role extends ReferencableElement.
 *         The 'name' element that is inherited from that type must be unique in the collection of roles
 *         defined on the parent type.
 *         This uniqueness must extend over the roles available on the type by
 *         inheritance.
 * 
 * <p>Java class for Role complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Role">
 *   <complexContent>
 *     <extension base="{http://www.ivoa.net/xml/VODML/v1}ReferableElement">
 *       <sequence>
 *         <element name="datatype" type="{http://www.ivoa.net/xml/VODML/v1}ElementRef"/>
 *         <element name="multiplicity" type="{http://www.ivoa.net/xml/VODML/v1}Multiplicity"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Role", propOrder = {
    "datatype",
    "multiplicity"
})
@XmlSeeAlso({
    Attribute.class,
    Relation.class
})
public abstract class Role
    extends ReferableElement
{

    /**
     * Reference to the type that plays the role represented by this Role.
     * 
     */
    @XmlElement(required = true)
    protected ElementRef datatype;
    /**
     * The multiplicity of the role (also called cardinality) indicates whether it must have a
     *                 value or may be without value, or possibly how many values are allowed.
     * 
     */
    @XmlElement(required = true)
    protected Multiplicity multiplicity;

    /**
     * Reference to the type that plays the role represented by this Role.
     * 
     * @return
     *     possible object is
     *     {@link ElementRef }
     *     
     */
    public ElementRef getDatatype() {
        return datatype;
    }

    /**
     * Sets the value of the datatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementRef }
     *     
     * @see #getDatatype()
     */
    public void setDatatype(ElementRef value) {
        this.datatype = value;
    }

    /**
     * The multiplicity of the role (also called cardinality) indicates whether it must have a
     *                 value or may be without value, or possibly how many values are allowed.
     * 
     * @return
     *     possible object is
     *     {@link Multiplicity }
     *     
     */
    public Multiplicity getMultiplicity() {
        return multiplicity;
    }

    /**
     * Sets the value of the multiplicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Multiplicity }
     *     
     * @see #getMultiplicity()
     */
    public void setMultiplicity(Multiplicity value) {
        this.multiplicity = value;
    }

}
