//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:06 AM EDT 
//


package org.ivoa.vodml.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Type used to indicate on attributes that they take values representing a concept defined in
 *         an identified semantic vocabulary (SKOS or RDFS), and/or restricted by being narrower/more specific than an
 *         identified "top" concept.
 *       
 * 
 * <p>Java class for SemanticConcept complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SemanticConcept">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="topConcept" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="vocabularyURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SemanticConcept", propOrder = {
    "topConcept",
    "vocabularyURI"
})
public class SemanticConcept {

    @XmlSchemaType(name = "anyURI")
    protected String topConcept;
    @XmlSchemaType(name = "anyURI")
    protected List<String> vocabularyURI;

    /**
     * Gets the value of the topConcept property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopConcept() {
        return topConcept;
    }

    /**
     * Sets the value of the topConcept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopConcept(String value) {
        this.topConcept = value;
    }

    /**
     * Gets the value of the vocabularyURI property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vocabularyURI property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVocabularyURI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getVocabularyURI() {
        if (vocabularyURI == null) {
            vocabularyURI = new ArrayList<String>();
        }
        return this.vocabularyURI;
    }

}
