//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Type used to indicate on attributes that they take values representing a concept defined in
 *         an identified semantic vocabulary (SKOS or RDFS), and/or restricted by being narrower/more specific than an
 *         identified "top" concept.
 * 
 * <p>Java class for SemanticConcept complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="SemanticConcept">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="topConcept" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         <element name="vocabularyURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SemanticConcept", propOrder = {
    "topConcept",
    "vocabularyURI"
})
public class SemanticConcept {

    /**
     * A URI identifiying a semantic concept that corresponds to the concept in the model.
     *             Values of a corresponding attributes must be URI-s identifiying objects that are narrower
     *             than the identified concept. This attribute may be null as
     *             certain vocabularies may not have a
     * 
     */
    @XmlSchemaType(name = "anyURI")
    protected String topConcept;
    /**
     * If no topConcept is defined, one or more explicit vocabularies can be provided from which the
     *             value must be obtained.
     * 
     */
    @XmlSchemaType(name = "anyURI")
    protected List<String> vocabularyURI;

    /**
     * A URI identifiying a semantic concept that corresponds to the concept in the model.
     *             Values of a corresponding attributes must be URI-s identifiying objects that are narrower
     *             than the identified concept. This attribute may be null as
     *             certain vocabularies may not have a
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopConcept() {
        return topConcept;
    }

    /**
     * Sets the value of the topConcept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getTopConcept()
     */
    public void setTopConcept(String value) {
        this.topConcept = value;
    }

    /**
     * If no topConcept is defined, one or more explicit vocabularies can be provided from which the
     *             value must be obtained.
     * 
     * Gets the value of the vocabularyURI property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vocabularyURI property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getVocabularyURI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the vocabularyURI property.
     */
    public List<String> getVocabularyURI() {
        if (vocabularyURI == null) {
            vocabularyURI = new ArrayList<>();
        }
        return this.vocabularyURI;
    }

}
