//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:06 AM EDT 
//


package org.ivoa.vodml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *       A special type of constraint that represents the common pattern where a subtype.
 *       would like to restrict certain aspects of a definition of a  roles defined on a super type.
 *       The constraint explicitly defines the datatype of the identified role. This new datatype MUST
 *       be a subtype of the declared datatype of the role that is being constrained. Similarly
 *       a new, more restrictive semantic concept  may be defined.
 *       
 * 
 * <p>Java class for SubsettedRole complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubsettedRole">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/VODML/v1}Constraint">
 *       &lt;sequence>
 *         &lt;element name="role" type="{http://www.ivoa.net/xml/VODML/v1}ElementRef"/>
 *         &lt;element name="datatype" type="{http://www.ivoa.net/xml/VODML/v1}ElementRef" minOccurs="0"/>
 *         &lt;element name="semanticconcept" type="{http://www.ivoa.net/xml/VODML/v1}SemanticConcept" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubsettedRole", propOrder = {
    "role",
    "datatype",
    "semanticconcept"
})
public class SubsettedRole
    extends Constraint
{

    @XmlElement(required = true)
    protected ElementRef role;
    protected ElementRef datatype;
    protected SemanticConcept semanticconcept;

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link ElementRef }
     *     
     */
    public ElementRef getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementRef }
     *     
     */
    public void setRole(ElementRef value) {
        this.role = value;
    }

    /**
     * Gets the value of the datatype property.
     * 
     * @return
     *     possible object is
     *     {@link ElementRef }
     *     
     */
    public ElementRef getDatatype() {
        return datatype;
    }

    /**
     * Sets the value of the datatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementRef }
     *     
     */
    public void setDatatype(ElementRef value) {
        this.datatype = value;
    }

    /**
     * Gets the value of the semanticconcept property.
     * 
     * @return
     *     possible object is
     *     {@link SemanticConcept }
     *     
     */
    public SemanticConcept getSemanticconcept() {
        return semanticconcept;
    }

    /**
     * Sets the value of the semanticconcept property.
     * 
     * @param value
     *     allowed object is
     *     {@link SemanticConcept }
     *     
     */
    public void setSemanticconcept(SemanticConcept value) {
        this.semanticconcept = value;
    }

}
