//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.votable.jaxb;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ivoa.votable.jaxb package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ivoa.votable.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VOTABLE }
     * 
     * @return
     *     the new instance of {@link VOTABLE }
     */
    public VOTABLE createVOTABLE() {
        return new VOTABLE();
    }

    /**
     * Create an instance of {@link AnyTEXT }
     * 
     * @return
     *     the new instance of {@link AnyTEXT }
     */
    public AnyTEXT createAnyTEXT() {
        return new AnyTEXT();
    }

    /**
     * Create an instance of {@link Definitions }
     * 
     * @return
     *     the new instance of {@link Definitions }
     */
    public Definitions createDefinitions() {
        return new Definitions();
    }

    /**
     * Create an instance of {@link CoordinateSystem }
     * 
     * @return
     *     the new instance of {@link CoordinateSystem }
     */
    public CoordinateSystem createCoordinateSystem() {
        return new CoordinateSystem();
    }

    /**
     * Create an instance of {@link Group }
     * 
     * @return
     *     the new instance of {@link Group }
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Param }
     * 
     * @return
     *     the new instance of {@link Param }
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Info }
     * 
     * @return
     *     the new instance of {@link Info }
     */
    public Info createInfo() {
        return new Info();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     * @return
     *     the new instance of {@link Resource }
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Min }
     * 
     * @return
     *     the new instance of {@link Min }
     */
    public Min createMin() {
        return new Min();
    }

    /**
     * Create an instance of {@link Max }
     * 
     * @return
     *     the new instance of {@link Max }
     */
    public Max createMax() {
        return new Max();
    }

    /**
     * Create an instance of {@link Option }
     * 
     * @return
     *     the new instance of {@link Option }
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link Values }
     * 
     * @return
     *     the new instance of {@link Values }
     */
    public Values createValues() {
        return new Values();
    }

    /**
     * Create an instance of {@link Link }
     * 
     * @return
     *     the new instance of {@link Link }
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Field }
     * 
     * @return
     *     the new instance of {@link Field }
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link FieldRef }
     * 
     * @return
     *     the new instance of {@link FieldRef }
     */
    public FieldRef createFieldRef() {
        return new FieldRef();
    }

    /**
     * Create an instance of {@link ParamRef }
     * 
     * @return
     *     the new instance of {@link ParamRef }
     */
    public ParamRef createParamRef() {
        return new ParamRef();
    }

    /**
     * Create an instance of {@link Data }
     * 
     * @return
     *     the new instance of {@link Data }
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link TableData }
     * 
     * @return
     *     the new instance of {@link TableData }
     */
    public TableData createTableData() {
        return new TableData();
    }

    /**
     * Create an instance of {@link Td }
     * 
     * @return
     *     the new instance of {@link Td }
     */
    public Td createTd() {
        return new Td();
    }

    /**
     * Create an instance of {@link Tr }
     * 
     * @return
     *     the new instance of {@link Tr }
     */
    public Tr createTr() {
        return new Tr();
    }

    /**
     * Create an instance of {@link FITS }
     * 
     * @return
     *     the new instance of {@link FITS }
     */
    public FITS createFITS() {
        return new FITS();
    }

    /**
     * Create an instance of {@link Binary }
     * 
     * @return
     *     the new instance of {@link Binary }
     */
    public Binary createBinary() {
        return new Binary();
    }

    /**
     * Create an instance of {@link Binary2 }
     * 
     * @return
     *     the new instance of {@link Binary2 }
     */
    public Binary2 createBinary2() {
        return new Binary2();
    }

    /**
     * Create an instance of {@link Stream }
     * 
     * @return
     *     the new instance of {@link Stream }
     */
    public Stream createStream() {
        return new Stream();
    }

    /**
     * Create an instance of {@link Table }
     * 
     * @return
     *     the new instance of {@link Table }
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link VODMLOptionMapping }
     * 
     * @return
     *     the new instance of {@link VODMLOptionMapping }
     */
    public VODMLOptionMapping createVODMLOptionMapping() {
        return new VODMLOptionMapping();
    }

}
