//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:04 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ivoa.net/xml/VOTable/v1.3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.ivoa.votable.jaxb;
