//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:04 AM EDT 
//


package org.ivoa.votable.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 	  Allows one to map particular values defined in a VALUES/OPTION list to enumeration literals
 * 	  in the VO-DML model or to a concept in a SKOS vocabulary.
 * 	  
 * 
 * <p>Java class for VODMLOptionMapping complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VODMLOptionMapping">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="LITERAL" type="{http://www.ivoa.net/xml/VOTable/v1.3}VODMLReference"/>
 *           &lt;element name="SEMANTICCONCEPT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLOptionMapping", propOrder = {
    "option",
    "semanticconcept",
    "literal"
})
public class VODMLOptionMapping {

    @XmlElement(name = "OPTION", required = true)
    protected String option;
    @XmlElement(name = "SEMANTICCONCEPT")
    protected String semanticconcept;
    @XmlElement(name = "LITERAL")
    protected String literal;

    /**
     * Gets the value of the option property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOPTION() {
        return option;
    }

    /**
     * Sets the value of the option property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOPTION(String value) {
        this.option = value;
    }

    /**
     * Gets the value of the semanticconcept property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEMANTICCONCEPT() {
        return semanticconcept;
    }

    /**
     * Sets the value of the semanticconcept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEMANTICCONCEPT(String value) {
        this.semanticconcept = value;
    }

    /**
     * Gets the value of the literal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLITERAL() {
        return literal;
    }

    /**
     * Sets the value of the literal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLITERAL(String value) {
        this.literal = value;
    }

}
