//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.votable.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Allows one to map particular values defined in a VALUES/OPTION list to enumeration literals
 * 	  in the VO-DML model or to a concept in a SKOS vocabulary.
 * 
 * <p>Java class for VODMLOptionMapping complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="VODMLOptionMapping">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="OPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <choice>
 *           <element name="LITERAL" type="{http://www.ivoa.net/xml/VOTable/v1.3}VODMLReference"/>
 *           <element name="SEMANTICCONCEPT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         </choice>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VODMLOptionMapping", propOrder = {
    "option",
    "semanticconcept",
    "literal"
})
public class VODMLOptionMapping {

    /**
     * The VOTable OPTION value that is being maped to enum literal or semantic concept.
     * 
     */
    @XmlElement(name = "OPTION", required = true)
    protected String option;
    /**
     * TBD anyURI as an identifier of concepts made sense for SKOS vocabularies. How about general semantic vocabularies?
     * 				I.e. is it ok for the type be xs:string iso xs:anyURI?
     * 
     */
    @XmlElement(name = "SEMANTICCONCEPT")
    protected String semanticconcept;
    @XmlElement(name = "LITERAL")
    protected String literal;

    /**
     * The VOTable OPTION value that is being maped to enum literal or semantic concept.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOPTION() {
        return option;
    }

    /**
     * Sets the value of the option property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getOPTION()
     */
    public void setOPTION(String value) {
        this.option = value;
    }

    /**
     * TBD anyURI as an identifier of concepts made sense for SKOS vocabularies. How about general semantic vocabularies?
     * 				I.e. is it ok for the type be xs:string iso xs:anyURI?
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEMANTICCONCEPT() {
        return semanticconcept;
    }

    /**
     * Sets the value of the semanticconcept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSEMANTICCONCEPT()
     */
    public void setSEMANTICCONCEPT(String value) {
        this.semanticconcept = value;
    }

    /**
     * Gets the value of the literal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLITERAL() {
        return literal;
    }

    /**
     * Sets the value of the literal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLITERAL(String value) {
        this.literal = value;
    }

}
