# location of jaxb .jar files
# required for xjc generation from XML schemas, and paths generation (needs to parse VO-DML docs using JAXB)
# need special version for ...
# see http://jaxb.kava.net
#jaxb.dir=C:/software/Java/jaxb-ri-20120218/lib
jaxb.dir=../WEB-INF/lib
jaxb=../../jaxb-gen