//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.instance.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Attribute complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Attribute">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <choice minOccurs="0">
 *           <element name="primitiveValue" type="{http://volute.g-vo.org/dm/vo-dml-instance/v0.x}PrimitiveValue"/>
 *           <element name="dataObject" type="{http://volute.g-vo.org/dm/vo-dml-instance/v0.x}DataObject"/>
 *         </choice>
 *       </sequence>
 *       <attribute name="vodmlRef" use="required" type="{http://volute.g-vo.org/dm/vo-dml-instance/v0.x}VODMLREF" />
 *       <attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="type" type="{http://volute.g-vo.org/dm/vo-dml-instance/v0.x}VODMLREF" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Attribute", propOrder = {
    "dataObject",
    "primitiveValue"
})
public class Attribute {

    protected DataObject dataObject;
    protected PrimitiveValue primitiveValue;
    @XmlAttribute(name = "vodmlRef", required = true)
    protected String vodmlRef;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the dataObject property.
     * 
     * @return
     *     possible object is
     *     {@link DataObject }
     *     
     */
    public DataObject getDataObject() {
        return dataObject;
    }

    /**
     * Sets the value of the dataObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataObject }
     *     
     */
    public void setDataObject(DataObject value) {
        this.dataObject = value;
    }

    /**
     * Gets the value of the primitiveValue property.
     * 
     * @return
     *     possible object is
     *     {@link PrimitiveValue }
     *     
     */
    public PrimitiveValue getPrimitiveValue() {
        return primitiveValue;
    }

    /**
     * Sets the value of the primitiveValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimitiveValue }
     *     
     */
    public void setPrimitiveValue(PrimitiveValue value) {
        this.primitiveValue = value;
    }

    /**
     * Gets the value of the vodmlRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVodmlRef() {
        return vodmlRef;
    }

    /**
     * Sets the value of the vodmlRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVodmlRef(String value) {
        this.vodmlRef = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
