//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.instance.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Collection complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Collection">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="object" type="{http://volute.g-vo.org/dm/vo-dml-instance/v0.x}Object" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="vomdmlRef" use="required" type="{http://volute.g-vo.org/dm/vo-dml-instance/v0.x}VODMLREF" />
 *       <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Collection", propOrder = {
    "objects"
})
public class Collection {

    /**
     * Objects contained in a parent container are always serialized inside the container.
     * 
     */
    @XmlElement(name = "object")
    protected List<VODMLObject> objects;
    @XmlAttribute(name = "vomdmlRef", required = true)
    protected String vomdmlRef;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Objects contained in a parent container are always serialized inside the container.
     * 
     * Gets the value of the objects property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objects property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getObjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VODMLObject }
     * </p>
     * 
     * 
     * @return
     *     The value of the objects property.
     */
    public List<VODMLObject> getObjects() {
        if (objects == null) {
            objects = new ArrayList<>();
        }
        return this.objects;
    }

    /**
     * Gets the value of the vomdmlRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVomdmlRef() {
        return vomdmlRef;
    }

    /**
     * Sets the value of the vomdmlRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVomdmlRef(String value) {
        this.vomdmlRef = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
