//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:05 AM EDT 
//


package org.ivoa.vodml.instance.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Instance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Instance">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="model" type="{http://volute.g-vo.org/dm/vo-dml-instance/v0.x}ModelLocation" maxOccurs="unbounded"/>
 *         &lt;element name="object" type="{http://volute.g-vo.org/dm/vo-dml-instance/v0.x}Object" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dataObject" type="{http://volute.g-vo.org/dm/vo-dml-instance/v0.x}DataObject" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Instance", propOrder = {
    "models",
    "objects",
    "dataObjects"
})
@XmlRootElement(name = "instance")
public class Instance {

    @XmlElement(name = "model", required = true)
    protected List<ModelLocation> models;
    @XmlElement(name = "object")
    protected List<VODMLObject> objects;
    @XmlElement(name = "dataObject")
    protected List<DataObject> dataObjects;

    /**
     * Gets the value of the models property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the models property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModelLocation }
     * 
     * 
     */
    public List<ModelLocation> getModels() {
        if (models == null) {
            models = new ArrayList<ModelLocation>();
        }
        return this.models;
    }

    /**
     * Gets the value of the objects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VODMLObject }
     * 
     * 
     */
    public List<VODMLObject> getObjects() {
        if (objects == null) {
            objects = new ArrayList<VODMLObject>();
        }
        return this.objects;
    }

    /**
     * Gets the value of the dataObjects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataObjects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataObjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataObject }
     * 
     * 
     */
    public List<DataObject> getDataObjects() {
        if (dataObjects == null) {
            dataObjects = new ArrayList<DataObject>();
        }
        return this.dataObjects;
    }

}
