//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:05 AM EDT 
//


package org.ivoa.vodml.instance.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *       This class describes the location of a data model's VO-DML and HTML documents.
 *       Note, these should eventually be derived form an appropriate Registry entry.
 *       Can also give include the prefix to be used in a particular instantiation document.
 *       
 * 
 * <p>Java class for ModelLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModelLocation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vodmlURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="documentationURL" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="vodmlrefPrefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelLocation", propOrder = {
    "vodmlURL",
    "documentationURL",
    "vodmlrefPrefix"
})
public class ModelLocation {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String vodmlURL;
    @XmlSchemaType(name = "anyURI")
    protected String documentationURL;
    @XmlElement(required = true)
    protected String vodmlrefPrefix;

    /**
     * Gets the value of the vodmlURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVodmlURL() {
        return vodmlURL;
    }

    /**
     * Sets the value of the vodmlURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVodmlURL(String value) {
        this.vodmlURL = value;
    }

    /**
     * Gets the value of the documentationURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentationURL() {
        return documentationURL;
    }

    /**
     * Sets the value of the documentationURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentationURL(String value) {
        this.documentationURL = value;
    }

    /**
     * Gets the value of the vodmlrefPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVodmlrefPrefix() {
        return vodmlrefPrefix;
    }

    /**
     * Sets the value of the vodmlrefPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVodmlrefPrefix(String value) {
        this.vodmlrefPrefix = value;
    }

}
