//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.instance.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * This class describes the location of a data model's VO-DML and HTML documents.
 *       Note, these should eventually be derived form an appropriate Registry entry.
 *       Can also give include the prefix to be used in a particular instantiation document.
 * 
 * <p>Java class for ModelLocation complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ModelLocation">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="vodmlURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         <element name="documentationURL" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         <element name="vodmlrefPrefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelLocation", propOrder = {
    "vodmlURL",
    "documentationURL",
    "vodmlrefPrefix"
})
public class ModelLocation {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String vodmlURL;
    @XmlSchemaType(name = "anyURI")
    protected String documentationURL;
    @XmlElement(required = true)
    protected String vodmlrefPrefix;

    /**
     * Gets the value of the vodmlURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVodmlURL() {
        return vodmlURL;
    }

    /**
     * Sets the value of the vodmlURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVodmlURL(String value) {
        this.vodmlURL = value;
    }

    /**
     * Gets the value of the documentationURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentationURL() {
        return documentationURL;
    }

    /**
     * Sets the value of the documentationURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentationURL(String value) {
        this.documentationURL = value;
    }

    /**
     * Gets the value of the vodmlrefPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVodmlrefPrefix() {
        return vodmlrefPrefix;
    }

    /**
     * Sets the value of the vodmlrefPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVodmlrefPrefix(String value) {
        this.vodmlrefPrefix = value;
    }

}
