//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 07:46:05 AM EDT 
//


package org.ivoa.vodml.instance.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *       Wrapper type for an Object Identifier. 
 *       Consists of a transientID, which is a long and acts as a key (see below).
 *       It also contains a publisherDID, and an externalID, which is a URL, possibly pointing into a registry.
 *       
 * 
 * <p>Java class for ObjectId complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectId">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transientID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="publisherDID" type="{http://volute.g-vo.org/dm/vo-dml-instance/v0.x}CustomId" minOccurs="0"/>
 *         &lt;element name="altID" type="{http://volute.g-vo.org/dm/vo-dml-instance/v0.x}AltId" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectId", propOrder = {
    "transientID",
    "publisherDID",
    "altID"
})
public class ObjectId {

    @XmlElement(required = true)
    protected String transientID;
    protected CustomId publisherDID;
    protected AltId altID;

    /**
     * Gets the value of the transientID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransientID() {
        return transientID;
    }

    /**
     * Sets the value of the transientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransientID(String value) {
        this.transientID = value;
    }

    /**
     * Gets the value of the publisherDID property.
     * 
     * @return
     *     possible object is
     *     {@link CustomId }
     *     
     */
    public CustomId getPublisherDID() {
        return publisherDID;
    }

    /**
     * Sets the value of the publisherDID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomId }
     *     
     */
    public void setPublisherDID(CustomId value) {
        this.publisherDID = value;
    }

    /**
     * Gets the value of the altID property.
     * 
     * @return
     *     possible object is
     *     {@link AltId }
     *     
     */
    public AltId getAltID() {
        return altID;
    }

    /**
     * Sets the value of the altID property.
     * 
     * @param value
     *     allowed object is
     *     {@link AltId }
     *     
     */
    public void setAltID(AltId value) {
        this.altID = value;
    }

}
