//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ivoa.vodml.instance.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Wrapper type for an Object Identifier. 
 *       Consists of a transientID, which is a long and acts as a key (see below).
 *       It also contains a publisherDID, and an externalID, which is a URL, possibly pointing into a registry.
 * 
 * <p>Java class for ObjectId complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ObjectId">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="transientID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="publisherDID" type="{http://volute.g-vo.org/dm/vo-dml-instance/v0.x}CustomId" minOccurs="0"/>
 *         <element name="altID" type="{http://volute.g-vo.org/dm/vo-dml-instance/v0.x}AltId" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectId", propOrder = {
    "transientID",
    "publisherDID",
    "altID"
})
public class ObjectId {

    @XmlElement(required = true)
    protected String transientID;
    protected CustomId publisherDID;
    protected AltId altID;

    /**
     * Gets the value of the transientID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransientID() {
        return transientID;
    }

    /**
     * Sets the value of the transientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransientID(String value) {
        this.transientID = value;
    }

    /**
     * Gets the value of the publisherDID property.
     * 
     * @return
     *     possible object is
     *     {@link CustomId }
     *     
     */
    public CustomId getPublisherDID() {
        return publisherDID;
    }

    /**
     * Sets the value of the publisherDID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomId }
     *     
     */
    public void setPublisherDID(CustomId value) {
        this.publisherDID = value;
    }

    /**
     * Gets the value of the altID property.
     * 
     * @return
     *     possible object is
     *     {@link AltId }
     *     
     */
    public AltId getAltID() {
        return altID;
    }

    /**
     * Sets the value of the altID property.
     * 
     * @param value
     *     allowed object is
     *     {@link AltId }
     *     
     */
    public void setAltID(AltId value) {
        this.altID = value;
    }

}
